# Site config

# Info 
title: pbnjk has a blog
author:
  name: PBnJK
  email: pedrobuitragons@gmail.com
description: >-
  Thoughts on computers and whatever else comes to mind

# URL
baseurl: ""
domain: "PBnJK.github.io"
url: "https://PBnJK.github.io"

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-feed

# Theme
minima:
  skin: dark

  social_links:
    - { platform: github, user_url: "https://github.com/PBnJK" }
    - { platform: bluesky, user_url: "https://pbnjk.bsky.social" }

# Collections
collections:
  tags:
    output: true
    permalink: /:collection/:categories:output_ext

header_pages:
  - about.md

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
