title: PBs Blog!
email: pedrobuitragons@gmail.com
description: >-
  Thoughts on computers and whatever else comes to mind
baseurl: ""
domain: "PBnJK.github.io"
url: "https://PBnJK.github.io"

github_username: PBnJK

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-feed

minima:
  skin: dark

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
