local t = require("tmpl_lyrics")

return t.Album({
	title = '"Os Mutantes"',
	year = "1968",
	artist = "Os Mutantes",
	genre = "Tropicália, Psychedelic Rock, Experimental Rock",

	date = {
		year = 2025,
		month = 10,
		day = 8,
	},
}, {
	t.img({
		src = "/assets/blog/covers/1968_os_mutantes_os_mutantes.jpg",
		width = "400",
	}),
	t.Subtitle("Arnaldo Baptista, Rita Lee, and Sérgio Dias"),
	t.p({
		"Os Mutantes (The Mutants) is",
		t.Footnote(1),
		[[
		a band started in 1966 by brothers Arnaldo
		Baptista and Sérgio Dias along with singer Rita Lee, during the height of the
		Tropicália movement in Brazil, which sought to mix popular Brazilian musical
		tradition with foreign styles. In this line, their 1968 self-titled debut album
		is a hodgepodge of influences, from The Beatles to Jimi Hendrix, Baião to African
		music—all backed by a generous heap of unconventional instrumentation and abstract
		lyricism, jumping between songs of love and critiques of the military dictatorship.
	]],
	}),
	t.img({
		src = "/assets/blog/os_mutantes_performing.jpg",
		width = "400",
	}),
	t.Subtitle("Fabulous!"),
	t.p([[
		Os Mutantes are also notable for their innovation, at a time where electric
		instruments were expensive and the phonographic industry in Brazil was far
		behind that of countries like the United States or England. Cláudio César Dias
		Baptista, brother of Arnaldo and Sérgio, built himself the guitar and bass used
		in most Mutantes records, as well as their effects pedals, amplifiers, etc.
	]]),
	t.Song({ title = "Panis et Circensis", en_title = "Bread and Circuses, in Latin" }, {
		t.Note('Based in part on the English version released on their "Tecnicolor" album.'),
		t.Lyric("00:22", "I wanted to sing", "Que eu quis cantar"),
		t.Lyric("00:25", "My song lighted by the sun", "Minha canção iluminada de sol"),
		t.Lyric("00:28", "I drew the flags over the sticks of the wind", "Soltei os panos sobre os mastros no ar"),
		t.Lyric("00:32", "I let loose tigers and lions on the backyards", "Soltei os tigres e os leões nos quintais"),
		t.Lyric("00:37", "But the people in the dining room", "Mas as pessoas na sala de jantar"),
		t.Lyric("00:41", "Are busy living and dying", "São ocupadas em nascer e morrer"),
		t.br(),
		t.Lyric("00:51", "I had a dagger of pure shiny steel made", "Mandei fazer de puro aço luminoso um punhal"),
		t.Lyric("00:58", "To kill my love and I did", "Para matar o meu amor e matei"),
		t.Lyric("01:02", "At five o' clock on the Central Avenue", "Às cinco horas na Avenida Central"),
		t.Lyric("01:06", "But the people in the dining room", "Mas as pessoas na sala de jantar"),
		t.Lyric("01:10", "Are busy living and dying", "São ocupadas em nascer e morrer"),
		t.br(),
		t.Lyric("01:21", {
			"I had them dream leaves on the ",
			t.InlineNote("solar's", 'Might refer to the "Solar da Fossa," an artist hangout spot'),
			" garden",
		}, "Mandei plantar folhas de sonho no jardim do solar"),
		t.Lyric("01:27", "The leaves know how to search for the sun", "As folhas sabem procurar pelo Sol"),
		t.Lyric("01:31", "And the roots to search, search", "E as raízes procurar, procurar"),
		t.Lyric("01:35", "But the people in the dining room", "Mas as pessoas na sala de jantar"),
		t.Lyric("01:39", "These people in the dining room", "Essas pessoas da sala de jantar"),
		t.br(),
		t.Lyric("01:43", "They're the people in the dining room", "São as pessoas da sala de jantar"),
		t.Lyric("01:47", "But the people in the dining room", "Mas as pessoas na sala de jantar"),
		t.Lyric("01:51", "Are busy living and dying", "São ocupadas em nascer e morrer"),
		t.br(),
		t.Lyric("02:29", "These people in the dining room", "Essas pessoas na sala de jantar"),
		t.Lyric("02:34", "These people in the dining room", "Essas pessoas na sala de jantar"),
		t.Lyric("02:38", "These people in the dining room", "Essas pessoas na sala de jantar"),
		t.Lyric("02:42", "These people in the dining room", "Essas pessoas na sala de jantar"),
		t.Lyric("02:45", "These people in the dining room", "Essas pessoas na sala de jantar"),
		t.Lyric("02:48", "These people in the dining room", "Essas pessoas na sala de jantar"),
		t.Lyric("02:52", "These people in the dining room", "Essas pessoas na sala de jantar"),
		t.Lyric("02:55", "These people in the dining room", "Essas pessoas na sala de jantar"),
		t.Lyric("02:58", "These people in the dining room", "Essas pessoas na sala de jantar"),
		t.Lyric("03:01", "These people in the dining room", "Essas pessoas na sala de jantar"),
		t.Lyric("03:04", "These people in the—", "Essas pessoas na sala—"),
		t.br(),
		t.Lyric("03:16", "— Pass me the salad, please", "— Me passa a salada pra mim, por favor"),
		t.Lyric(
			"03:20",
			"— Pass me the bread, please, just one more piece",
			"— Passa o pão, por favor, só mais um pedacinho"
		),
	}),
	t.Song({ title = "A Minha Menina", en_title = "My Girl" }, {
		t.Lyric("00:00", "— Cough, everybody coughing!", "— Tosse, todo mundo tossindo!"),
		t.Lyric("00:01", "— Ha ha ha ha!", "— Ha ha ha ha!"),
		t.br(),
		t.Lyric("00:23", "She's my girl", "Ela é minha menina"),
		t.Lyric("00:29", "And I'm her boy", "E eu sou o menino dela"),
		t.Lyric("00:34", "She's my love", "Ela é o meu amor"),
		t.Lyric("00:40", "And I'm her love, entirely hers", "E eu sou o amor todinho dela"),
		t.br(),
		t.Lyric("00:45", "(Come on, huh!)", "(Chama, hu!)"),
		t.Lyric("00:47", "The silver moon hid away", "A lua prateada se escondeu"),
		t.Lyric("00:52", "And the golden sun appeared", "E o sol dourado apareceu"),
		t.Lyric("00:58", "A new day dawned, smelling of joy", "Amanheceu um lindo dia, cheirando alegria"),
		t.Lyric("01:05", "Because I dreamed and woke up thinking about her", "Pois eu sonhei e acordei pensando nela"),
		t.br(),
		t.Lyric("01:12", "Because she's my girl", "Pois ela é minha menina"),
		t.Lyric("01:18", "And I'm her boy", "E eu sou o menino dela"),
		t.Lyric("01:22", "She's my love", "Ela é o meu amor"),
		t.Lyric("01:29", "And I'm her love, entirely hers", "E eu sou o amor todinho dela"),
		t.br(),
		t.Lyric("01:39", "The rosebush has already sprouted roses", "A roseira já deu rosas"),
		t.Lyric("01:44", "And the rose I earned was her", "E a rosa que eu ganhei foi ela"),
		t.Lyric(
			"01:50",
			"For her, I let my heart get in front of reason",
			"Por ela eu ponho o meu coração na frente da razão"
		),
		t.Lyric("01:56", "And I'll tell everyone how much I like her", "E vou dizer pra todo mundo como gosto dela"),
		t.br(),
		t.Lyric("02:04", "Because she's my girl", "Pois ela é minha menina"),
		t.Lyric("02:10", "And I'm her boy", "E eu sou o menino dela"),
		t.Lyric("02:15", "She's my love", "Ela é o meu amor"),
		t.Lyric("02:21", "And I'm her love, entirely hers", "E eu sou o amor todinho dela"),
		t.br(),
		t.Lyric("02:26", "(Uh!)", "(Uh!)"),
		t.Lyric("03:08", "The silver moon hid away", "A lua prateada se escondeu"),
		t.Lyric("03:14", "And the golden sun appeared", "E o sol dourado apareceu"),
		t.Lyric("03:19", "A new day dawned, smelling of joy", "Amanheceu um lindo dia, cheirando alegria"),
		t.Lyric("03:26", "Because I dreamed and woke up thinking about her", "Pois eu sonhei e acordei pensando nela"),
		t.br(),
		t.Lyric("03:33", "Because she's my girl", "Pois ela é minha menina"),
		t.Lyric("03:39", "And I'm her boy", "E eu sou o menino dela"),
		t.Lyric("03:44", "She's my love", "Ela é o meu amor"),
		t.Lyric("03:50", "And I'm her love, entirely hers", "E eu sou o amor todinho dela"),
		t.br(),
		t.Lyric("03:56", "My girl, my girl", "Minha menina, minha menina"),
		t.Lyric("04:09", "My girl, my girl", "Minha menina, minha menina"),
		t.Lyric("04:13", "My girl, my girl", "Minha menina, minha menina"),
		t.Lyric("04:20", "My girl, my girl", "Minha menina, minha menina"),
	}),
	t.Song({ title = "O Relógio", en_title = "The Watch" }, {
		t.Lyric("00:07", "My watch stopped", "Meu relógio parou"),
		t.Lyric("00:18", "It forever gave up being", "Desistiu pra sempre de ser"),
		t.Lyric("00:23", "Anti-magnetic", "Antimagnético"),
		t.Lyric("00:29", {
			"Twenty two ",
			t.InlineNote("jewels", "As in the jewel bearings in a watch"),
		}, "Vinte e dois rubis"),
		t.br(),
		t.Lyric("00:39", "I wound it up and thought", "Eu dei corda e pensei"),
		t.Lyric("00:46", "That the watch would live", "Que o relógio iria viver"),
		t.Lyric("00:52", "To tell the time", "Pra dizer a hora"),
		t.Lyric("00:57", "Of your arrival", "De você chegar"),
		t.br(),
		t.Lyric("01:07", "It didn't run and I cried", "Não andou e eu chorei"),
		t.Lyric("01:13", "Two still hands, laughing", "Dois ponteiros parados a rir"),
		t.Lyric("01:19", "They're waterproof", "São à prova d'água"),
		t.Lyric("01:23", "Twenty two jewels", "Vinte e dois rubis"),
		t.br(),
		t.Lyric("01:37", "What great luck of mine", "Que vantagem eu levei"),
		t.Lyric("01:45", "To have a watch", "Em ter um relógio"),
		t.Lyric("01:47", "That is Swiss or English", "Que é suíço ou inglês"),
		t.Lyric("01:53", "And doesn't run", "Sem andar"),
		t.Lyric("01:56", "What time will you arrive?", "A que horas você vai chegar?"),
		t.Text("(instrumental)"),
		t.Lyric("02:40", "And I threw myself into the sea", "E no mar me atirei"),
		t.Lyric("02:47", "Watch in hands, and thought", "Com o relógio nas mãos e pensei"),
		t.Lyric("02:52", "It's waterproof", "Ele é à prova d'água"),
		t.Lyric("02:56", "Twenty two jewels", "Vinte dois rubis"),
	}),
	t.Song({ title = "Adeus Maria Fulô", en_title = "Goodbye Maria Fulô" }, {
		t.Note('Goodbye Maria Fulô—fulô being a corruption of "flor," meaning flower. Goodbye Mary Flower!'),

		t.Lyric("00:56", "Goodbye, I'm going, my dear", "Adeus, vou-me embora, meu bem"),
		t.Lyric("00:59", "Crying doesn't help anyone", "Chorar não ajuda ninguém"),
		t.Lyric("01:02", "Wipe your tears of pain", "Enxugue o seu pranto de dor"),
		t.Lyric("01:04", {
			"For the ",
			t.InlineNote(
				"drought",
				"Droughts are a recurring motif in the music of the Brazilian Northeast, where they are an unfortunate reality, and is very commonly paired with the themes of migration and leaving behind loved ones.\nSivuca, the composer, hails from the Northeast"
			),
			" has only just started",
		}, "Que a seca mal começou"),
		t.br(),
		t.Lyric("01:13", "Goodbye, I'm going, my dear", "Adeus, vou-me embora, meu bem"),
		t.Lyric("01:16", "Crying doesn't help anyone", "Chorar não ajuda ninguém"),
		t.Lyric("01:18", "Wipe your tears of pain", "Enxugue o seu pranto de dor"),
		t.Lyric("01:21", "For the drought has only just started", "Que a seca mal começou"),
		t.br(),
		t.Lyric("01:30", "Goodbye, I'm going, Maria", "Adeus, vou-me embora, Maria"),
		t.Lyric("01:33", "Flower of my heart", "Fulô do meu coração"),
		t.Lyric("01:36", "I'll come back someday", "Eu voltarei qualquer dia"),
		t.Lyric("01:38", "It just needs to rain in the backlands", "É só chover no sertão"),
		t.Lyric("01:41", "And the days until my return", "E os dias da minha volta"),
		t.Lyric("01:44", "I count on my hand", "Eu conto na minha mão"),
		t.br(),
		t.Lyric("01:47", "Goodbye Maria Fulô", "Adeus, Maria Fulô"),
		t.Lyric("01:50", "The quince tree dried out", "Marmeleiro amarelou"),
		t.Lyric("01:53", "Goodbye Maria Fulô", "Adeus, Maria Fulô"),
		t.Lyric("01:56", "The water spring ran dry", "Olho d'água esturricou"),
		t.br(),
		t.Lyric("02:04", "Goodbye, I'm going, my dear", "Adeus, vou-me embora, meu bem"),
		t.Lyric("02:07", "Crying doesn't help anyone", "Chorar não ajuda ninguém"),
		t.Lyric("02:10", "Wipe your tears of pain", "Enxugue seu pranto de dor"),
		t.Lyric("02:12", "For the drought has only just started", "Que a seca mal começou"),
		t.Lyric("02:18", "For the drought has only just started", "Que a seca mal começou"),
		t.Lyric("02:23", "For the drought has only just started", "Que a seca mal começou"),
		t.Lyric("02:29", "For the drought has only just started", "Que a seca mal começou"),
	}),
	t.Song({ title = "Baby", en_title = "Baby" }, {
		t.Note(
			'"Baby," famous in the voice of Gal Costa, parodies the upper-class, westernized culture that was on the rise at the time of its writing.'
		),
		t.Lyric("00:16", "You", "Você"),
		t.Lyric("00:20", "Need to know of the pool", "Precisa saber da piscina"),
		t.Lyric("00:23", "Of margarine, of Carolina, of gasoline", "Da margarina, da Carolina, da gasolina"),
		t.Lyric("00:30", "You need to know about me", "Você precisa saber de mim"),
		t.br(),
		t.Lyric("00:40", "Baby, baby", "Baby, baby"),
		t.Lyric("00:45", "I know that's how it is", "Eu sei que é assim"),
		t.Lyric("00:49", "Baby, baby", "Baby, baby"),
		t.Lyric("00:54", "I know that's how it is", "Eu sei que é assim"),
		t.br(),
		t.Lyric("00:58", "You", "Você"),
		t.Lyric("01:01", "Need to have an ice cream", "Precisa tomar um sorvete"),
		t.Lyric("01:04", "In the diner", "Na lanchonete"),
		t.Lyric("01:06", "Walk with us, see me up close", "Andar com gente, me ver de perto"),
		t.Lyric("01:11", {
			"Listen to that ",
			t.InlineNote("Roberto", 'Roberto Carlos, highly influential heartthrob musician, dubbed "The King."'),
			" song",
		}, "Ouvir aquela canção do Roberto"),
		t.br(),
		t.Lyric("01:21", "Baby, baby", "Baby, baby"),
		t.Lyric("01:26", "How long has it been", "Há quanto tempo"),
		t.Lyric("01:30", "Baby, baby", "Baby, baby"),
		t.Lyric("01:35", "How long has it been", "Há quanto tempo"),
		t.br(),
		t.Lyric("01:39", "You", "Você"),
		t.Lyric("01:42", "Need to learn English", "Precisa aprender inglês"),
		t.Lyric("01:46", "You need to learn what I know", "Precisa aprender o que eu sei"),
		t.Lyric("01:49", "And what I don't know anymore", "E o que eu não sei mais"),
		t.Lyric("01:51", "(And what I don't know anymore)", "(E o que eu não sei mais)"),
		t.br(),
		t.Lyric("01:56", "I don't know", "Não sei"),
		t.Lyric("01:59", "With me it's all been blue", "Comigo vai tudo azul"),
		t.Lyric("02:03", "With you everything's in peace", "Contigo vai tudo em paz"),
		t.br(),
		t.Lyric("02:08", "We live in the best city", "Vivemos na melhor cidade"),
		t.Lyric("02:10", "Of South America", "Da América do Sul"),
		t.Lyric("02:12", "Of South America", "Da América do Sul"),
		t.br(),
		t.Lyric("02:15", "You need", "Você precisa"),
		t.Lyric("02:17", "You need", "Você precisa"),
		t.Lyric("02:22", "I don't know", "Não sei"),
		t.Lyric("02:25", "Read it on my shirt", "Leia na minha camisa"),
		t.br(),
		t.Lyric("02:31", "Baby, baby, I love you", "Baby, baby, I love you"),
		t.Lyric("02:39", "Baby, baby, I love you", "Baby, baby, I love you"),
		t.Lyric("02:47", "Baby, baby, I love you", "Baby, baby, I love you"),
		t.Lyric("02:56", "Baby, baby...", "Baby, baby..."),
	}),
	t.Song({ title = "Senhor F", en_title = "Mr. F" }, {
		t.Lyric("00:05", "Mr. F", "O Senhor F"),
		t.Lyric("00:08", "Dreams of being", "Vive a querer"),
		t.Lyric("00:11", "Mr. X", "Ser Senhor X"),
		t.Lyric("00:14", "But is afraid of never going back", "Mas tem medo de nunca voltar"),
		t.Lyric("00:17", "To being Mr. F again", "A ser o Senhor F outra vez"),
		t.br(),
		t.Lyric("00:21", "Mr. X", "O Senhor X"),
		t.Lyric("00:25", "Is the hero (X)", "É o herói (X)"),
		t.Lyric("00:28", "That on TV (X)", "Que na TV (X)"),
		t.Lyric("00:31", "Never loses his hat", "Nunca perde o seu chapéu"),
		t.Lyric("00:34", "And makes Mr. F dream", "E faz o Senhor F sonhar"),
		t.br(),
		t.Lyric("00:38", "Dream of having", "Sonhar em ter"),
		t.Lyric("00:41", "For the others to see", "Pros outros ver"),
		t.Lyric("00:45", "Blue eyes", "Olhos azuis"),
		t.Lyric("00:48", "A car just like Mr. X", "Ter um carro igual ao de X"),
		t.Lyric("00:52", "And winning over the boss' wife", "E conquistar a mulher do patrão"),
		t.br(),
		t.Lyric("00:59", "Give your boss a kick", "Dê um chute no patrão"),
		t.Lyric("01:03", "Give your boss a kick", "Dê um chute no patrão"),
		t.Lyric("01:05", "Give your boss a kick", "Dê um chute no patrão"),
		t.Text("(instrumental)"),
		t.Lyric("01:28", "You also", "Você também"),
		t.Lyric("01:31", "Want to be somebody", "Quer ser alguém"),
		t.Lyric("01:35", "To abandon it all", "Abandonar"),
		t.Lyric("01:38", "But are afraid of forgetting", "Mas tem medo de esquecer"),
		t.Lyric("01:41", {
			t.InlineNote(
				"Your handkerchief and documents again",
				"From a Caetano Veloso song, which talks about a young man strolling through the streets of dictatorship-era Brazil"
			),
		}, "O lenço e o documento outra vez"),
		t.br(),
		t.Lyric(
			"01:46",
			"Give your boss a kick (Extra, extra, extra)",
			"Dê um chute no patrão (Extra, extra, extra)"
		),
		t.Lyric(
			"01:49",
			"Give your boss a kick (Give your boss a kick)",
			"Dê um chute no patrão (Dê um chute no patrão)"
		),
		t.Lyric("01:53", "Give your boss a kick", "Dê um chute no patrão"),
	}),
	t.Song({ title = "Bat Macumba", en_title = "Bat Macumba" }, {
		t.Note([[
			Now, "Bat Macumba," Macumba being a blanket term for the wide umbrella of
			Afro-Brazilian religions (sometimes pejorative, though that's not the case
			here.) Notice the shape that the lyrics make, and see if you can relate it
			to a pun on the song title about a certain masked vigilante.
		]]),
		t.Lyric("00:23", "Bat Macumba ê ê, Bat Macumba obá"),
		t.Lyric("00:29", "Bat Macumba ê ê, Bat Macumba obá"),
		t.Lyric("00:32", "Bat Macumba ê ê, Bat Macumba obá"),
		t.Lyric("00:36", "Bat Macumba ê ê, Bat Macumba o"),
		t.Lyric("00:40", "Bat Macumba ê ê, Bat Macumba"),
		t.Lyric("00:44", "Bat Macumba ê ê, Bat Macum"),
		t.Lyric("00:48", "Bat Macumba ê ê, Bat Ma"),
		t.Lyric("00:52", "Bat Macumba ê ê, Bat"),
		t.Lyric("00:56", "Bat Macumba ê ê, Ba"),
		t.Lyric("01:00", "Bat Macumba ê ê"),
		t.Lyric("01:03", "Bat Macumba ê"),
		t.Lyric("01:06", "Bat Macumba"),
		t.Lyric("01:10", "Bat Macum"),
		t.Lyric("01:13", "Bat Ma"),
		t.Lyric("01:18", "Bat"),
		t.Lyric("01:22", "Ba"),
		t.Lyric("01:25", "Bat"),
		t.Lyric("01:30", "Bat Ma"),
		t.Lyric("01:33", "Bat Macum"),
		t.Lyric("01:37", "Bat Macumba"),
		t.Lyric("01:41", "Bat Macumba ê"),
		t.Lyric("01:45", "Bat Macumba ê ê"),
		t.Lyric("01:49", "Bat Macumba ê ê, Ba"),
		t.Lyric("01:54", "Bat Macumba ê ê, Bat"),
		t.Lyric("01:58", "Bat Macumba ê ê, Bat Ma"),
		t.Lyric("02:03", "Bat Macumba ê ê, Bat Macum"),
		t.Lyric("02:06", "Bat Macumba ê ê, Bat Macumba"),
		t.Lyric("02:10", "Bat Macumba ê ê, Bat Macumba o"),
		t.Lyric("02:14", "Bat Macumba ê ê, Bat Macumba obá"),
		t.Lyric("02:18", "Bat Macumba ê ê, Bat Macumba obá"),
		t.Lyric("02:22", "Bat Macumba ê ê, Bat Macumba obá"),
		t.Lyric("03:02", "Bat Macumba ê ê, Bat Macumba obá"),
	}),
	t.Song({ title = "Le Premier Bonheur du Jour", en_title = "The First Happiness of the Day" }, {
		t.Note({
			"This song is in french, which I do not speak. See footnote",
			t.Footnote(2),
			" for the source for this translation. Thank you to @frenchrescue on YouTube!",
		}),
		t.Lyric("00:18", "The first happiness of the day", " Le premier bonheur du jour"),
		t.Lyric("00:23", "It's a ribbon of sunshine", " C'est un ruban de soleil"),
		t.Lyric("00:28", "Which is wound around your hand", " Qui s'enroule sur ta main"),
		t.Lyric("00:33", "And gently strokes my shoulder", " Et caresse mon épaule"),
		t.br(),
		t.Lyric("00:38", "It's the breath of the sea", " C'est la souffle de la mère"),
		t.Lyric("00:43", "And the beach that awaits", " Et la plage qui attend"),
		t.Lyric("00:48", "It's the bird that sang", " C'est l'oiseau qui a chanté"),
		t.Lyric("00:53", "On the branch of the fig tree", " Sur la branche du figuier"),
		t.br(),
		t.Lyric("01:48", "The first sorrow of the day", " La premier chagrin du jour"),
		t.Lyric("01:52", "It's the door that closes", " C'est la porte qui se ferme"),
		t.Lyric("01:57", "The car that goes away", " La voiture qui s'en va"),
		t.Lyric("02:02", "The silence that settles", " Le silence qui s'installe"),
		t.br(),
		t.Lyric("02:07", "But you come back soon", " Mais bien vite tu reviens"),
		t.Lyric("02:12", "And my life is getting back to normal", " Et ma vie reprend son cours"),
		t.Lyric("02:17", "The last happiness of the day", " Le denier bonheur du jour"),
		t.Lyric("02:22", "It's the lamp that switched off", " C'est la lampe qui s'éteint"),
	}),
	t.Song({ title = "Trem Fantasma", en_title = "Ghost Train" }, {
		t.Lyric(
			"00:23",
			{ "Four hundred ", t.InlineNote("cruzeiros", "Old Brazilian currency") },
			" Quatrocentos cruzeiros"
		),
		t.Lyric("00:28", "Old men buy, frightened", " Velhos compram com medo"),
		t.Lyric("00:31", "From the ticket booth", " Da mão do bilheteiro"),
		t.Lyric("00:34", "Admissions to the ghost train", " As entradas do trem fantasma"),
		t.br(),
		t.Lyric("00:39", "Him and his girlfriend", " Ele e a namorada"),
		t.Lyric("00:43", "He doesn't think of anything", " Ele não pensa em nada"),
		t.Lyric("00:46", "She gets scared", " Ela fica assustada"),
		t.br(),
		t.Lyric(
			"00:51",
			{ "Four hundred cruzeiros of ", t.InlineNote("power", 'Like in "horsepower"') },
			" Quatrocentos cruzeiros de força"
		),
		t.Lyric("00:55", "Drag the young man and the lady", " Arrastam o rapaz e a moça"),
		t.Lyric("00:59", "To the place in", " Para o lugar em"),
		t.Lyric("01:01", "Shiny CinemaScope", " CinemaScope brilhante"),
		t.br(),
		t.Lyric("01:06", "The giant mountain", " A montanha gigante"),
		t.Lyric("01:08", "Of green generals", " De generais verdejantes"),
		t.Lyric("01:13", "And it appears in the distance", " E aparece distante"),
		t.Lyric("01:16", "The train on the shiny mirror", " O trem no espelho brilhante"),
		t.Lyric("01:20", "The kiss, the first kiss", " O beijo, o primeiro beijo"),
		t.Lyric("01:24", "Shatters the mirror", " Arrebenta o espelho"),
		t.br(),
		t.Lyric("01:38", "Four hundred cruzeiros", " Quatrocentos cruzeiros"),
		t.Lyric("01:42", "Four hundred bats of power", " Quatrocentos morcegos de força"),
		t.Lyric("01:47", "The kiss, the young man, and the lady", " O beijo, o rapaz e a moça"),
		t.br(),
		t.Lyric("01:51", "The train in the water", " O trem dentro d'água"),
		t.Lyric("01:53", "The still pool", " A piscina parada"),
		t.Lyric("01:57", "She doesn't think of anything", " Ela não pensa em nada"),
		t.Lyric("02:01", "He thinks but doesn't say", " Ele pensa e não diz"),
		t.Lyric("02:04", "Where there's a lot of water, everything's happy", " Onde tem muita água tudo é feliz"),
		t.br(),
		t.Lyric("02:09", "The first kiss", " O primeiro beijo"),
		t.Lyric("02:12", "Four hundred cruzeiros", " Quatrocentos cruzeiros"),
		t.Lyric("02:16", {
			"Joe ",
			t.InlineNote(
				"40HPs of thrills",
				'"HPs" as in horsepower. Also, this is a reference to an old car ad (see footnote 3)'
			),
		}, " Zé quarenta HPs de emoção"),
		t.br(),
		t.Lyric("02:20", {
			t.InlineNote(
				"Coffin Joe",
				'Classic Brazilian horror movie character, an undertaker, to round out the "dark ride" theme of the song'
			),
		}, " O Zé do Caixão"),
		t.Lyric("02:23", "Brings forth the creatures of creation", " Traz os bichos da criação"),
		t.Lyric("02:29", "To the gate and—", " Até o portão e—"),
		t.br(),
		t.Lyric("02:33", "The session's over", " Terminou a sessão"),
		t.Lyric("02:36", "Four hundred cruzeiros", " Quatrocentos cruzeiros"),
		t.Lyric("02:39", "Old men buy, frightened", " Velhos compram com medo"),
		t.Lyric("02:42", "Him and his girlfriend", " Ele e a namorada"),
		t.Lyric("02:46", "She doesn't think of anything", " Ela não pensa em nada"),
		t.Lyric("02:50", "He secretly thinks", " Ele pensa em segredo"),
		t.Lyric("02:54", "He secretly thinks", " Ele pensa em segredo"),
		t.Lyric("02:58", "He secretly thinks", " Ele pensa em segredo"),
		t.Lyric("03:02", "He secretly thinks", " Ele pensa em segredo"),
		t.Lyric("03:05", "He secretly thinks...", " Ele pensa em segredo..."),
	}),
	t.Song(
		{ title = "Tempo no Tempo (Once Was a Time I Thought)", en_title = "Time in Time (Once Was a Time I Thought)" },
		{
			t.Note('Cover of "Once Was a Time I Thought" by "The Mamas & The Papas."'),
			t.Lyric("00:00", "Hallelujah", " Aleluia"),
			t.Lyric("00:11", "I want to be with my Lord", " Eu quero estar com meu Senhor"),
			t.br(),
			t.Lyric(
				"00:28",
				"There's always a time in time when the body of man rots",
				" Há sempre um tempo no tempo em que o corpo do homem apodrece"
			),
			t.Lyric(
				"00:32",
				"And his tired, sorrowful soul sinks into the ground",
				" E sua alma cansada, penada, se afunda no chão"
			),
			t.br(),
			t.Lyric(
				"00:35",
				"And the wizard of luxury, his hood lowered, crying on a niche, sycophant of trash",
				" E o bruxo do luxo baixado o capucho chorando num nicho capacho do lixo"
			),
			t.Lyric("00:40", "Whims will not be coming back", " Caprichos não mais voltarão"),
			t.br(),
			t.Lyric(
				"00:42",
				"There once was time when time stopped passing by",
				" Já houve um tempo em que o tempo parou de passar"
			),
			t.Lyric(
				"00:47",
				"And a so-called homo sapiens didn't know how to harness it",
				" E um tal de homo sapiens não soube disso aproveitar"
			),
			t.br(),
			t.Lyric("00:51", "Crying, smiling, talking about shutting up", " Chorando, sorrindo, falando em calar"),
			t.Lyric(
				"00:54",
				"Thinking about thinking once time stops passing by",
				" Pensando em pensar quando o tempo parar de passar"
			),
			t.br(),
			t.Lyric(
				"00:58",
				"There's always a time in time when the body of man rots",
				" Há sempre um tempo no tempo em que o corpo do homem apodrece"
			),
			t.Lyric(
				"01:01",
				"And his tired, sorrowful soul sinks into the ground",
				" E sua alma cansada, penada, se afunda no chão"
			),
			t.br(),
			t.Lyric(
				"01:05",
				"And the wizard of luxury, his hood lowered, crying on a niche, sycophant of trash",
				" E o bruxo do luxo baixado o capucho chorando num nicho capacho do lixo"
			),
			t.Lyric("01:10", "Whims will not be coming back", " Caprichos não mais voltarão"),
			t.br(),
			t.Lyric(
				"01:12",
				"But if between tears you find yourself and you think you're crying",
				" Mas se entre lágrimas você se achar e pensar que está a chorar"
			),
			t.Lyric("01:19", "This was the time in which time is", " Este era o tempo em que o tempo é"),
		}
	),
	t.Song({ title = "Ave Gengis Khan", en_title = "Hail Gengis Khan" }, {
		t.Lyric("00:26", "Hail Gengis Khan", " Ave Gengis Khan"),
		t.Lyric("00:37", "Hail Gengis Khan", " Ave Gengis Khan"),
		t.Text("(instrumental)"),
		t.Lyric("02:43", "Hail Gengis Khan", " Ave Gengis Khan"),
		t.Lyric("02:54", "Hail Gengis Khan", " Ave Gengis Khan"),
	}),
	t.FootnoteSection(
		[[
		Nowadays, only Sérgio Dias is left of the original formation. Rita Lee was kicked
		out of the band in 1972 and unfortunately passed away in 2023, while Arnaldo
		Baptista left in 1973 due to issues with drug abuse (he is doing much better
		now!) Both of them led successful solo careers, with Rita Lee often being called
		the Brazilian “Queen of Rock.”
	]],
		t.a({
			href = "https://www.youtube.com/watch?v=nsOoltvk0sk",
			"Le Premier Bonheur du Jour Translation by frenchrescue",
		}),
		{
			"“Renault Gordini: ",
			t.a({
				href = "https://www.youtube.com/watch?v=UXgjuQAEUKs",
				"40HPs of thrills!",
			}),
			"” From a time when 40HP was enought to thrill ya.",
		}
	),
})
