local t = require("tmpl_lyrics")

return t.Album({
	title = "Força Bruta",
	artist = "Jorge Ben",
	genre = { "Samba", "MPB" },
	year = 1970,

	date = {
		year = 2026,
		month = 5,
		day = 13,
	},
}, {
	t.ZoomableImage(
		"/assets/blog/covers/1970_jorge_ben_forca_bruta.jpg",
		"Força Bruta album cover, depicting Jorge Ben singing into a microphone with his hands cupped over his mouth",
		400,
		400
	),
	t.p({
		--t.Pronounce("Força Bruta", "forca_bruta_title"),
		"Força Bruta",
		" (Brute Force) is ",
		--t.Pronounce("Jorge Ben", "jorge_ben"),
		"Jorge Ben",
		[['s seventh studio album, released in 1970. Following the major success of
		his psychedelic 1969 self-titled,
	]],
		t.i("Força Bruta"),
		[[
		sees Jorge Ben settle into a more relaxed “samba soul” groove, and also marks
		his second studio collaboration with backing band
	]],
		t.i("Trio Mocotó,"),
		" pictured below:",
	}),
	t.figure({
		t.ZoomableImage("/assets/blog/jorge_ben_e_trio_mocoto.jpg", "Jorge Ben playing with Trio Mocotó", 400, 400),
		t.figcaption([[
			Jorge Ben (middle) posing with Trio Mocotó. Clockwise from the top: Fritz Escovão,
			Nereu Gargalo, and João Parahyba. Photo from 1971.
		]]),
	}),
	t.p([[
		The album was recorded in one single night, mostly unrehearsed and semi-improvised,
		with occasional string and brass arrangements being added later.
	]]),
	t.Song({
		title = "Oba, Here She Comes",
		en_title = "Oba, Lá Vem Ela",
	}, {
		t.Lyric(
			"00:17",
			{ t.InlineNote("Oba", "Happy interjection, like “wow!” or “yay!”"), ", here she comes" },
			"Oba, lá vem ela"
		),
		t.Lyric("00:22", "I've got my eyes on her", "Estou de olho nela"),
		t.Lyric("00:27", "Oba, here she comes", "Oba, lá vem ela"),
		t.Lyric("00:32", "I've got my eyes on her", "Estou de olho nela"),
		t.br(),
		t.Lyric("00:37", "I don't care if she doesn't look at me", "Não me importo que ela não me olhe"),
		t.Lyric("00:43", "Doesn't say anything or even know I exist", "Não diga nada e não saiba que eu existo"),
		t.Lyric("00:46", "Or who I am", "Quem eu sou"),
		t.Lyric("00:48", "Because I know very well who she is", "Pois eu sei muito bem quem é ela"),
		t.Lyric("00:51", "And I'm happy just seeing her pass by, oba", "E fico contente só em ver ela passar, oba"),
		t.br(),
		t.Lyric("00:56", "Oba, here she comes", "Oba, lá vem ela"),
		t.Lyric("01:01", "I've got my eyes on her", "Estou de olho nela"),
		t.Lyric("01:06", "Oba, here she comes", "Oba, lá vem ela"),
		t.Lyric("01:11", "I've got my eyes on her", "Estou de olho nela"),
		t.br(),
		t.Lyric("01:16", "The night is beautiful", "A noite é linda"),
		t.Lyric("01:21", "And her, even more so", "E ela mais ainda"),
		t.Lyric("01:26", "All in pink", "Todinha de rosa"),
		t.Lyric("01:29", "More beautiful, sweeter", "Mais linda, mais meiga"),
		t.Lyric("01:34", "Than a rose", "Que uma rosa"),
		t.br(),
		t.Lyric("01:40", {
			"Oba, here she comes (eh, ",
			t.InlineNote(
				"comanche",
				"Nickname given by Jorge to Trio Mocotó drummer João Parahyba (see footnote 1 for details)"
			),
			")",
		}, "Oba, lá vem ela (eh, comanche)"),
		t.Lyric(
			"01:45",
			"I've got my eyes on her (eh mamma, eh mamma say)",
			"Estou de olho nela (ê mamma, ê mamma say)"
		),
		t.Lyric("01:50", "Oba, here she comes (eh, comanche)", "Oba, lá vem ela (ê, comanche)"),
		t.Lyric("01:55", "I've got my eyes on her", "Estou de olho nela"),
		t.br(),
		t.Lyric("02:01", "I don't care what people say, what they think", "Não me importo que falem, que pensem"),
		t.Lyric("02:06", "Because without knowing it, she's my joy", "Pois sem saber, ela é minha alegria"),
		t.Lyric("02:11", "She has the smell of a flower", "Ela tem um perfume de uma flor"),
		t.Lyric("02:13", "Whose name I don't know", "Que eu não sei o nome"),
		t.Lyric("02:16", "But it must have a beautiful name like her", "Mas ela deve ter um nome bonito igual a ela"),
		t.Lyric("02:20", "Oba, oba, oba, oba, oba, oba", "Oba, oba, oba, oba, oba, oba"),
		t.br(),
		t.Lyric("02:24", "Oba, here she comes (eh, comanche)", "Oba, lá vem ela (ei, comanche)"),
		t.Lyric("02:29", "I've got my eyes on her", "Estou de olho nela"),
		t.Lyric("02:33", "Oba, here she comes", "Oba, lá vem ela"),
		t.Lyric("02:38", "I've got my eyes on her", "Estou de olho nela"),
		t.Text("(instrumental)"),
		t.Lyric("03:05", "And how can I say yes?", "E como dizer sim"),
		t.Lyric("03:08", "And how can I say yes?", "E como dizer sim"),
		t.Lyric("03:10", "Oh comanche, comanche, comanche, comanche", "Ô, comanche, comanche, comanche, comanche"),
		t.br(),
		t.Lyric("03:14", "Oba, here she comes, eh, hey", "Oba, lá vem ela, eh, hey"),
		t.Lyric("03:18", "I've got my eyes on her", "Eu estou de olho nela"),
		t.Lyric("03:22", "Oba, comanche, oh eh-eh", "Ô, comanche, ô eh-eh"),
		t.Lyric("03:27", "I've got my eyes on her", "Estou de olho nela"),
		t.Text("(scatting commences)"),
		t.Lyric("03:31", "Hey, comanche, oh", "Ei, comanche, oh"),
		t.Lyric("03:34", "Eh mamma, eh mamma-ma, comanche", "E mama, e mama-ma, comanche"),
		t.Lyric(
			"03:37",
			"I've had my eyes on her for a while, for so long",
			"Eu estou de olho nela há muito, há muito tempo"
		),
		t.Lyric("03:40", "Oba, here she comes, I've got my eyes on her", "Oba, lá vem ela, eu estou de olho nela"),
		t.Lyric("03:43", "(Hit it, comanche!!!)", "(Senta o pau, comanche!!!)"),
		t.Lyric("03:46", "I've got my eyes on her", "Eu estou de olho nela"),
		t.Lyric("03:48", "Coma-ma-ma-ma-mancheiro", "Coma-ma-ma-ma-mancheiro"),
		t.Lyric("03:49", "Comancheiro eh, for so long, oh", "Comancheiro ê, há muito tempo, oh"),
		t.Lyric("03:53", "And how can I say yes?", "E como dizer sim"),
		t.Lyric("03:54", "Oh, comanche", "Ô, comanche"),
		t.Lyric("03:56", "And how can I say yes, hey, hey, hey, hey, hey", "E como dizer sim, ei, ei, ei, ei, ei"),
		t.Lyric("04:00", "Comanche, oh, oh", "Comanche, oh, oh"),
		t.Lyric("04:02", {
			"(Start wrapping it up, ",
			t.InlineNote(
				"Manel",
				"Probably Jorge cueing Manoel Barenbein, credited as producer on the album, to start fading us out"
			),
			")",
		}, "(E vai acabando, Manel)"),
		t.Lyric("04:05", "'cause I've got my eyes on her", "Que eu estou de olho nela"),
		t.Lyric("04:07", "Comanche, hey, hey, eh...", "Comanche, ei, ei, eh..."),
	}),
	t.Song({
		title = "Zé Canjica",
	}, {
		t.Note({
			"“Zé Canjica” ",
			t.i("could"),
			[[
			be translated as something like “Johnny Porridge”, but really it's just a
			funny pet name given to Jorge Ben by the ex-girlfriend he sings about in this
			tune.
		]],
		}),
		t.Lyric("00:01", "(Company, quick march!)", "(Companhia, ordinário, marche!)"),
		t.Lyric("00:17", "(Company, halt!)", "(Companhia, alto!)"),
		t.br(),
		t.Lyric(
			"00:27",
			"It's raining, and the rain is going to soak someone",
			"Está chovendo e a chuva vai molhar alguém"
		),
		t.Lyric(
			"00:35",
			"That in another time fell all wet into my arms",
			"Que outrora caía toda molhada nos braços meus"
		),
		t.Lyric("00:39", "It's not true, it can't be", "Não é verdade não, não pode ser"),
		t.Lyric("00:44", "It's not true, it can't be", "Não é verdade não, não pode ser"),
		t.br(),
		t.Lyric("00:48", "Silence, go away", "Silêncio, vai embora"),
		t.Lyric("00:53", "Leave me alone, I'm sorry", "Me deixa, perdão"),
		t.Lyric("00:57", "Silence, go away", "Silêncio, vai embora"),
		t.Lyric("01:02", "Leave me alone, I'm sorry", "Me deixa, perdão"),
		t.br(),
		t.Lyric("01:07", "I'm sorry, friends, guys", "Me desculpem, meus amigos, gente"),
		t.Lyric("01:11", "If I'm confused and sad", "Se eu estou confuso e triste"),
		t.Lyric("01:16", "And even ill-tempered", "E até mal humorado"),
		t.br(),
		t.Lyric("01:21", "But it's just that I'm no longer", "Mas é que eu já não sou"),
		t.Lyric("01:24", "My love's boyfriend", "O namorado do meu amor"),
		t.Lyric(
			"01:29",
			"But it's just that I'm no longer (but it's just that I'm no longer)",
			"Mas é que eu já não sou (mas é que eu já não sou)"
		),
		t.Lyric("01:33", "My love's boyfriend", "O namorado do meu amor"),
		t.br(),
		t.Lyric("01:39", {
			t.InlineNote(
				"I know my luck's not been the best",
				[[
					He actually uses the idiomatic expression “the tide's not right for fishing,”
					used to express lack of luck (often with girls specifically.) On the next line he
					sings that he “won't give up *fishing* [...],” completing this little joke
				]]
			),
		}, "Sei que a minha maré não está pra peixe"),
		t.Lyric("01:43", "But I won't give up trying because", "Mas eu não vou desistir de pescar porque"),
		t.Lyric("01:46", "Inside me there's still", "Pois ainda resta em mim"),
		t.Lyric("01:48", "A glimmer of hope and a will to live", "Um fio de esperança e a vontade de viver"),
		t.Lyric("01:52", "To win her over again", "Pra conseguir conquistar novamente ela"),
		t.Lyric("01:56", "To win her over again", "Pra conseguir conquistar novamente ela"),
		t.br(),
		t.Lyric("02:01", "Silence, go away", "Silêncio, vai embora"),
		t.Lyric("02:06", "Leave me alone, I'm sorry", "Me deixa, perdão"),
		t.Lyric("02:10", "Silence, go away", "Silêncio, vai embora"),
		t.Lyric("02:15", "Leave me alone, I'm sorry", "Me deixa, perdão"),
		t.Lyric("02:19", "Zé canjica (company! Good troop)", "Zé Canjica (companhia! Boa tropa)"),
		t.br(),
		t.Lyric("02:34", {
			t.InlineNote(
				"(The phone)",
				"This is not a T/L note or cultural context, just... man, who uses a rotary dial as percussion? I love this album"
			),
		}, "(O telefone)"),
		t.br(),
		t.Lyric("02:50", "Oh, Zé Canjica (company, quick, ah)", "Oh, Zé Canjica (companhia, ordinário, ah)"),
		t.Lyric("02:58", "But it's just that I'm no longer", "Mas é que eu já não sou"),
		t.Lyric("03:01", "My love's Zé Canjica", "O Zé Canjica do meu amor"),
		t.br(),
		t.Lyric(
			"03:10",
			"But it's just that I'm no longer (It's not all right, Zé Canjica)",
			"Mas é que eu já não sou (Tudo não tá direito, Zé Canjica)"
		),
		t.br(),
		t.Lyric(
			"03:15",
			"My love's Zé Canjica (belly in, chest out)",
			"O Zé Canjica do meu amor (barriga pra dentro, peito pra fora)"
		),
		t.Lyric("03:19", "Silence, go away", "Silêncio, vai embora"),
		t.Lyric(
			"03:24",
			"Leave me alone, I'm sorry (the company's in tip-top shape)",
			"Me deixa, perdão (a companhia está um aço)"
		),
		t.Lyric("03:29", "Silence, go away (one, two)", "Silêncio, vai embora (um, dois)"),
		t.Lyric("03:33", "Leave me alone, I'm sorry (one, two, one, two)", "Me deixa, perdão (um, dois, um, dois)"),
		t.br(),
		t.Lyric("03:39", "One, two (three, four)", "Um, dois (três, quatro)"),
		t.Lyric("03:41", "One, two (three, four)", "Um, dois (três, quatro)"),
		t.Lyric("03:43", "One, two (three, four)", "Um, dois (três, quatro)"),
		t.Lyric("03:45", "One, two (three, four)", "Um, dois (três, quatro)"),
		t.Lyric("03:47", "One, two...", "Um, dois..."),
	}),
	t.Song({
		title = "Domenica Domingava num Domingo Linda Toda de Branco",
		en_title = "Domenica Sundayed on a Sunday Beautiful All in White",
	}, {
		t.Note({
			"The name “Domenica” has the same etymological roots as “Domingo” (Sunday) in ",
			t.span({ style = "font-style: normal;", "“dominicus”" }),
			[[
			(“of the Lord.”) “Domingar” (to Sunday) is an expression meaning to loiter,
			like having a “lazy Sunday.” So this song is just an excuse to make Sunday
			puns :-D
		]],
		}),
		t.Lyric("00:05", "— Domenica...", "— Domenica..."),
		t.Lyric("00:11", "— Domenica...", "— Domenica..."),
		t.br(),
		t.Lyric("00:16", "I'll write a love anthem", "Eu vou compor um hino de amor"),
		t.Lyric("00:20", "For Domenica", "Para Domenica"),
		t.Lyric("00:24", "In honor of the angel", "Em homenagem ao anjo"),
		t.Lyric("00:27", "And wonder that she is", "E a maravilha que ela é"),
		t.br(),
		t.Lyric("00:31", "Domenica, Domenica, Domenica, Domenica", "Domenica, Domenica, Domenica, Domenica"),
		t.br(),
		t.Lyric("00:40", "Because I have faith that when God hears", "Pois eu tenho fé que quando Deus ouvir"),
		t.Lyric("00:45", "My love anthem", "Meu hino de amor"),
		t.Lyric("00:48", "I'll turn Domenica into", "Eu vou fazer da Domenica"),
		t.Lyric("00:51", "My guardian angel and my woman", "Meu anjo da guarda e minha mulher"),
		t.br(),
		t.Lyric("00:56", "Domenica, Domenica, Domenica, Domenica", "Domenica, Domenica, Domenica, Domenica"),
		t.Lyric("01:05", "Domenica! Domenica!", "Domenica! Domenica!"),
		t.br(),
		t.Lyric("01:10", "All of my sadness ends", "Toda a minha tristeza se acaba"),
		t.Lyric("01:13", "And my happiness starts with you", "E minha alegria começa em você"),
		t.Lyric("01:18", "Domenica, blessed woman", "Domenica, bendita mulher"),
		t.Lyric("01:21", "I love you and I believe in you", "Eu te amo eu te acredito"),
		t.Lyric("01:23", "I like you a lot, Domenica!", "Eu gosto muito de você, Domenica!"),
		t.br(),
		t.Lyric("01:25", "Domenica, Domenica, Domenica, Domenica", "Domenica, Domenica, Domenica, Domenica"),
		t.br(),
		t.Lyric("01:37", "I'll write a love anthem", "Eu vou compor um hino de amor"),
		t.Lyric("01:37", "For Domenica", "Para Domenica"),
		t.Lyric("01:44", "In honor of the angel", "Em homenagem ao anjo"),
		t.Lyric("01:44", "And wonder that she is", "E a maravilha que ela é"),
		t.br(),
		t.Lyric("01:53", "Domenica, Domenica, Domenica, Domenica", "Domenica, Domenica, Domenica, Domenica"),
		t.br(),
		t.Lyric("02:02", "Because I have faith that when God hears", "Pois eu tenho fé que quando Deus ouvir"),
		t.Lyric("02:06", "My love anthem", "Meu hino de amor"),
		t.Lyric("02:10", "I'll turn Domenica into", "Eu vou fazer da Domenica"),
		t.Lyric("02:13", "My guardian angel and my woman, Domenica!", "Meu anjo da guarda e minha mulher, Domenica!"),
		t.br(),
		t.Lyric("02:18", "Domenica, Domenica, Domenica, Domenica", "Domenica, Domenica, Domenica, Domenica"),
		t.Lyric("02:26", "Domenica! Domenica!", "Domenica! Domenica!"),
		t.br(),
		t.Lyric("02:31", "All of my sadness ends", "Toda a minha tristeza se acaba"),
		t.Lyric("02:35", "And my happiness starts with you", "E minha alegria começa em você"),
		t.Lyric("02:39", "Domenica, blessed woman", "Domenica bendita mulher"),
		t.Lyric("02:43", "I love you and I believe in you", "Eu te amo eu te acredito"),
		t.Lyric("02:45", "I like you a lot, Domenica...", "Eu gosto muito de você, Domenica..."),
		t.br(),
		t.Lyric("02:51", "Domenica, Domenica, Domenica, Domenica", "Domenica, Domenica, Domenica, Domenica"),
		t.Lyric("02:59", "Domenica, Domenica, Domenica, Domenica...", "Domenica, Domenica, Domenica, Domenica..."),
		t.Lyric("03:11", "(I love you Domenica, I love you Domenica)", "(Eu te amo Domenica, eu te amo Domenica)"),
		t.Lyric("03:22", "(Domenica, sundayed on a Sunday)", "(Domenica, domingava num domingo)"),
		t.Lyric("03:29", "(Domenica, sundayed on a Sunday)", "(Domenica, domingava num domingo)"),
		t.Lyric("03:36", "(All in white)", "(Toda de branca)"),
	}),
	t.Song({
		title = "Charles Jr.",
	}, {
		t.Note({
			[[
			This song features callbacks to two tracks from Jorge Ben's previous album,
			referencing the Charles character from “Charles, Anjo 45” (Charles, 45 Angel,)
			as well as the general theme of the song “Descobri que Sou um Anjo“ (I Found
			Out that I'm an Angel.) I've included some notes about the real-life Charles
			at the bottom of the page (see footnote]],
			t.Footnote(2),
			")",
		}),
		t.Lyric("00:13", "— Eh, comanche", "— Ê, comanche"),
		t.Lyric("00:21", "— Comancheiro", "— Comancheiro"),
		t.Lyric("00:26", "— Mamma say, comanche", "— Mama say, comanche"),
		t.Lyric("00:33", "— Amazing...", "— Sensacional..."),
		t.Lyric("00:42", "— Eh, comanche", "— Ê, comanche"),
		t.Text("(instrumental)"),
		t.Lyric("01:48", "My name's Charles Jr. (go, go)", "Eu me chamo Charles Junior (vai, vai)"),
		t.Lyric("01:52", "I'm also an angel (go, go)", "Eu também sou um anjo (vai, vai)"),
		t.Lyric("01:56", "My name's Charles Jr. (go, go)", "Eu me chamo Charles Junior (vai, vai)"),
		t.Lyric("02:01", "I'm also an angel (go, go)", "Eu também sou um anjo (vai, vai)"),
		t.br(),
		t.Lyric("02:06", "But I don't want to be the first (go, go)", "Mas eu não quero ser o primeiro (vai, vai)"),
		t.Lyric("02:10", "Or to be better than anyone else (go, go)", "Nem ser melhor do que ninguém (vai, vai)"),
		t.Lyric("02:15", "I just want to live in peace (go, go)", "Só quero viver em paz (vai, vai)"),
		t.Lyric("02:19", "And to be treated as an equal (go, go)", "E ser tratado de igual para igual (vai, vai)"),
		t.br(),
		t.Lyric(
			"02:24",
			"Because in return for my affection, and for my love (go, go)",
			"Pois em troca do meu carinho, do meu amor (vai, vai)"
		),
		t.Lyric(
			"02:29",
			"I want to be understood and to be considered (go, go)",
			"Eu quero ser compreendido e considerado (vai, vai)"
		),
		t.Lyric("02:33", "And, if possible, also loved (go, go)", "E se for possível, também amado (vai, vai)"),
		t.Lyric(
			"02:38",
			"Because it doesn't matter what I have (go, go)",
			"Pois não importa o que eu tenho (vai, vai)"
		),
		t.Lyric(
			"02:42",
			"But instead what I can do with what I have (go, go)",
			"E sim o que eu possa fazer com o que eu tenho (vai, vai)"
		),
		t.br(),
		t.Lyric("02:47", "Because I'm no longer (no, no)", "Pois eu já não sou (não, não)"),
		t.Lyric("02:52", "What my brothers were (no, no)", "O que foram os meus irmãos (não, não)"),
		t.Lyric("02:56", {
			"Because I was born out of a ",
			t.InlineNote(
				"free womb",
				[[
				The Ventre Livre Law (Free Womb Law) was a law passed in Brazil in 1871 that
				granted freedom to the children of slaves. This law was an important (if much belated
				and imperfect) first step for the abolitionist movement in the country.
			]]
			),
			" (go, go)",
		}, "Pois eu nasci de um ventre livre (vai, vai)"),
		t.Lyric("03:01", {
			"I was born out of a free womb in the ",
			t.InlineNote(
				"20th century",
				"Slavery would only be abolished in Brazil in 1888. Jorge Ben was born in 1939, a mere 51 years later."
			),
			" (go, go)",
		}, "Nasci de um ventre livre no século 20 (vai, vai)"),
		t.br(),
		t.Lyric("03:05", "I have faith, love and faith (go, go)", "Eu tenho fé, e o amor e a fé (vai, vai)"),
		t.Lyric("03:10", "In the 21st century (go, go)", "No século 21 (vai, vai)"),
		t.Lyric(
			"03:14",
			"Where the scientific, astronomical, and medicinal accomplishments (go, go)",
			"Onde as conquistas científicas, espaciais, medicinais (vai, vai)"
		),
		t.Lyric("03:19", "And the unity of the peoples (go, go)", "E a confraternização dos povos (vai, vai)"),
		t.Lyric("03:24", "And the humility of a king (go, go)", "E a humildade de um rei (vai, vai)"),
		t.Lyric("03:28", "Will be the weapons of victory (go, go)", "Serão as armas da vitória (vai, vai)"),
		t.Lyric("03:33", "For universal peace (go, go)", "Para a paz universal (vai, vai)"),
		t.br(),
		t.Lyric("03:38", "And the whole world will hear (go, go)", "E o mundo todo vai ouvir (vai, vai)"),
		t.Lyric("03:42", "And the whole world will know (go, go)", "E o mundo todo vai saber (vai, vai)"),
		t.br(),
		t.Lyric("03:47", "That my name's Charles Jr. (go, go)", "Que eu me chamo Charles Junior (vai, vai)"),
		t.Lyric("03:51", "I'm also an angel (go, go)", "Eu também sou um anjo (vai, vai)"),
		t.Lyric("03:55", "My name's Charles Jr. (go, go)", "Eu me chamo Charles Junior (vai, vai)"),
		t.Lyric("04:00", "I'm also an angel (go, go)", "Eu também sou um anjo (vai, vai)"),
		t.Lyric("04:05", "My name's Charles Jr. (go, go)", "Eu me chamo Charles Junior (vai, vai)"),
		t.Lyric("04:09", "I'm also an angel (go, go)", "Eu também sou um anjo (vai, vai)"),
		t.Text("(instrumental)"),
		t.Lyric("04:42", "— Comanche!", "Comanche!"),
		t.Lyric("04:44", "— Comancheiro!", "Comancheiro!"),
		t.Lyric("04:48", "— My name's Charles Jr.!", "Eu me chamo Charles Junior!"),
		t.br(),
		t.Lyric("05:10", "— Eh, comanche", "— Ê, comanche"),
		t.Lyric("05:15", "— Amazing...", "— Sensacional..."),
		t.br(),
		t.Lyric("05:28", "That my name's Charles Jr. (go, go)", "Eu me chamo Charles Junior (vai, vai)"),
		t.Lyric("05:33", "I'm also an angel (go, go)", "Eu também sou um anjo (vai, vai)"),
		t.Lyric("05:37", "That my name's Charles Jr. (go, go)", "Eu me chamo Charles Junior (vai, vai)"),
		t.Lyric("05:42", "I'm also an angel (go, go)", "Eu também sou um anjo (vai, vai)"),
		t.Lyric(
			"05:46",
			{ t.InlineNote("Nereu Gargalo", "Trio Mocotó's pandeiro (tambourine) player"), " (go, go)" },
			"Nereu Gargalo (vai vai)"
		),
		t.Lyric(
			"05:51",
			{ t.InlineNote("Joãozinho da Parahyba", "Trio Mocotó's drummer"), " (go, go)" },
			"Joãozinho da Parahyba (vai, vai)"
		),
		t.Lyric(
			"05:55",
			{ t.InlineNote("Fritz Escovão", "Trio Mocotó's cuíca (tongue drum) player"), " (go, go)" },
			"Fritz Escovão (vai, vai)"
		),
		t.Lyric("06:00", {
			t.InlineNote(
				"Cláudio, the bass man",
				[[
				May also be “Cláudio, the short man.” No idea who this guy is... No Cláudios
				are credited on this album. Perhaps a friend of Jorge?
			]]
			),
		}, "Cláudio, o homem baixo"),
	}),
	t.Song({
		title = "Pulo, Pulo",
		en_title = "I Jump, I Jump",
	}, {
		t.Lyric("00:00", "— Hm, hm, hm, mh", "— Hum, hum, hum, hum"),
		t.Lyric("00:01", "— Recording I jump, I jump, I jump", "— Gravando, pulo, pulo, pulo"),
		t.br(),
		t.Lyric("00:18", "I jump, I jump, I jump, and don't fall", "Pulo, pulo, pulo e não caio"),
		t.Lyric("00:20", "I jump, I jump, I jump, and if I fall", "Pulo, pulo, pulo, e se eu caio"),
		t.Lyric("00:23", "I fall inside of my love's", "Eu caio dentro do balaio"),
		t.Lyric("00:25", "Basket of flowers", "De flores do meu amor"),
		t.br(),
		t.Lyric("00:30", "I jump, I jump, I jump, and don't fall", "Pulo, pulo, pulo e não caio"),
		t.Lyric("00:32", "I jump, I jump, I jump, and if I fall", "Pulo, pulo, pulo, e se eu caio"),
		t.Lyric("00:34", "I fall inside of my love's", "Eu caio dentro do balaio"),
		t.Lyric("00:37", "Basket of flowers", "De flores do meu amor"),
		t.br(),
		t.Lyric("00:41", "The basket has roses, has cloves, daisies", "O balaio tem rosas, tem cravos, margaridas"),
		t.Lyric(
			"00:45",
			"Tulips, hydrangeas, has lilies, violets, everlasting flower",
			"Tulipas, hortênsias, tem lírios, violetas, sempre-viva"
		),
		t.Lyric("00:50", {
			t.InlineNote("Fuchsias", "Specifically the fuchsia hybrida, known as “princess' earrings” in Brazil"),
			", orchids, jasmines",
		}, "Brinco-de-princesa, orquídeas, jasmins"),
		t.Lyric("00:55", {
			"Has ",
			t.InlineNote(
				"heartsease, that's what she is for me",
				"Heartsease is the viola tricolor, known as “perfect-love” in Brazil—thus “that's what she is for me”"
			),
		}, "Tem amor-perfeito, é o que ela é pra mim"),
		t.Text("(repeats)"),
	}),
	t.Song({
		title = "Apareceu Aparecida",
		en_title = "Aparecida Appeared",
	}, {
		t.Note([[
			Aparecida is one of the titles of Mary, the mother of Jesus (“Nossa Senhora
			Aparecida,” literally “Our Lady, the Appeared.”) It was also a very popular
			woman's name for a while.
		]]),
		t.Lyric("00:19", "Ai, ai, ai, Aparecida appeared", "Ai, ai, ai, apareceu Aparecida"),
		t.Lyric("00:23", "Ai, ai, ai, she's appeared, Aparecida", "Ai, ai, ai, Aparecida apareceu"),
		t.Lyric("00:27", "Ai, ai, ai, the thing I wanted most happened", "Ai, ai, ai, aconteceu o que eu mais queria"),
		t.Lyric(
			"00:32",
			"Ai, ai, ai, it happened, the thing I wanted most",
			"Ai, ai, ai o que eu mais queria aconteceu"
		),
		t.br(),
		t.Lyric("00:37", "I set side my pride", "Deixei de lado o meu orgulho"),
		t.Lyric(
			"00:40",
			"Because I saw how it was ugly, useless, and so unhappy",
			"Pois eu vi como era feio, inútil e tão infeliz"
		),
		t.Lyric(
			"00:46",
			"I found out that life is beautiful, the sun rises for everyone",
			"Descobri que a vida é bela, o sol nasceu pra todos"
		),
		t.Lyric(
			"00:50",
			"Love is beautiful, she wanted me and now I'm happy",
			"O amor é lindo, ela me quis e agora eu sou feliz"
		),
		t.br(),
		t.Lyric("00:54", "Ai, ai, ai, Aparecida appeared", "Ai, ai, ai apareceu Aparecida"),
		t.Lyric("00:58", "Ai, ai, ai, she's appeared, Aparecida", "Ai, ai, ai Aparecida apareceu"),
		t.Lyric("01:02", "Ai, ai, ai, the thing I wanted most happened", "Ai, ai, ai aconteceu o que eu mais queria"),
		t.Lyric(
			"01:07",
			"Ai, ai, ai, it happened, the thing I wanted most",
			"Ai, ai, ai o que eu mais queria aconteceu"
		),
		t.br(),
		t.Lyric("01:12", "Roll stones, roll stones", "Rola pedra, rola pedra"),
		t.Lyric("01:16", "Those that roll stones don't laze around", "Quem rola pedra não fica à toa"),
		t.Lyric("01:21", "The more I roll stones", "Quanto mais eu rolo pedra"),
		t.Lyric("01:25", "The better things get", "Mais a coisa fica boa"),
		t.br(),
		t.Lyric("01:29", "Ai, ai, ai, Aparecida appeared", "Ai, ai, ai apareceu Aparecida"),
		t.Lyric("01:33", "Ai, ai, ai, she's appeared, Aparecida", "Ai, ai, ai Aparecida apareceu"),
		t.Lyric("01:38", "Ai, ai, ai, the thing I wanted most happened", "Ai, ai, ai aconteceu o que eu mais queria"),
		t.Lyric(
			"01:42",
			"Ai, ai, ai, it happened, the thing I wanted most",
			"Ai, ai, ai o que eu mais queria aconteceu"
		),
		t.Text("(instrumental)"),
		t.Lyric("02:05", "Ai, ai, ai, Aparecida appeared", "Ai, ai, ai apareceu Aparecida"),
		t.Lyric("02:09", "Ai, ai, ai, she's appeared, Aparecida", "Ai, ai, ai Aparecida apareceu"),
		t.Lyric("02:14", "Ai, ai, ai, the thing I wanted most happened", "Ai, ai, ai aconteceu o que eu mais queria"),
		t.Lyric(
			"02:18",
			"Ai, ai, ai, it happened, the thing I wanted most",
			"Ai, ai, ai o que eu mais queria aconteceu"
		),
		t.br(),
		t.Lyric("02:23", "Ah! Aparecida, appeeared", "Ah! Apareceu, Aparecida"),
		t.Lyric("02:25", "She's appeared, Aparecida", "Aparecida, apareceu"),
		t.Lyric("02:28", "The thing I wanted most, happened", "Aconteceu, o que eu mais queria"),
		t.Lyric("02:30", "It happened, the thing I wanted most", "O que eu mais queria, aconteceu"),
		t.br(),
		t.Lyric("02:32", "Ai, ai, ai, Aparecida appeared", "Ai, ai, ai apareceu Aparecida"),
		t.Lyric("02:36", "Ai, ai, ai, she's appeared, Aparecida", "Ai, ai, ai Aparecida apareceu (ei cumpadi!)"),
		t.Lyric("02:40", "Ai, ai, ai, the thing I wanted most happened", "Ai, ai, ai aconteceu o que eu mais queria"),
		t.Lyric(
			"02:44",
			"Ai, ai, ai, it happened, the thing I wanted most (eh, partner!)",
			"Ai, ai, ai o que eu mais queria aconteceu (ê cumpadi!)"
		),
		t.Lyric("02:49", "Ai, ai, ai (eh partner!)", "Ai, ai, ai (ê cumpadi!)"),
		t.br(),
		t.Lyric("02:57", "Ai, ai, ai, Aparecida appeared", "Eh, ai, ai, ai apareceu Aparecida"),
		t.Lyric(
			"03:02",
			"Oi! Ai, ai, ai, she's appeared, Aparecida (ai, ai, ai)",
			"Oi! (Ai, ai, ai) ai, ai, ai Aparecida apareceu"
		),
		t.Lyric("03:06", "Ai, ai, ai, the thing I wanted most happened", "Ai, ai, ai aconteceu o que eu mais queria"),
		t.Lyric("03:10", "Ai, ai, ai, it happened, the thing I wanted most", "Ai, ai, ai o que eu mais queria..."),
		t.Text("(etc.)"),
	}),
	t.Song({
		title = "O Telefone Tocou Novamente",
		en_title = "The Phone Rang Again",
	}, {
		t.Note("The big hit of the album."),
		t.Lyric("00:15", "(Hello?)", "(Alô?)"),
		t.br(),
		t.Lyric("00:16", "The phone rang again", "O telefone tocou novamente"),
		t.Lyric("00:22", "I went to answer but it wasn't my love calling", "Fui atender e não era o meu amor"),
		t.Lyric("00:28", "Is she still very mad at me?", "Será que ela ainda está muito zangada comigo?"),
		t.br(),
		t.Lyric("00:34", "What a shame", "Que pena"),
		t.Lyric("00:37", "What a shame", "Que pena"),
		t.Lyric("00:39", "What a shame", "Que pena"),
		t.Lyric("00:42", "What a shame", "Que pena"),
		t.br(),
		t.Lyric("00:45", "Because only she", "Pois só ela"),
		t.Lyric("00:46", "Understands me and helps me", "Me entende e me acode"),
		t.Lyric("00:50", "In my fall or in my rise", "Na queda ou na ascensão"),
		t.Lyric("00:51", "She's the peace to my war", "Ela é a paz da minha guerra"),
		t.Lyric("00:54", "She's my state of mind", "Ela é meu estado de espírito"),
		t.Lyric("00:57", "She's my protection", "Ela é a minha proteção"),
		t.br(),
		t.Lyric("01:01", "What a shame", "Que pena"),
		t.Lyric("01:04", "What a shame", "Que pena"),
		t.Lyric("01:07", "What a shame", "Que pena"),
		t.Lyric("01:10", "What a shame", "Que pena"),
		t.br(),
		t.Lyric("01:14", "With her, I'm more me", "Com ela eu sou mais eu"),
		t.Lyric("01:19", "With her, I'm an angel", "Com ela eu sou um anjo"),
		t.Lyric("01:25", "With her, I'm a child", "Com ela eu sou criança"),
		t.Lyric("01:28", "I am peace", "Eu sou a paz"),
		t.Lyric("01:30", "I am love", "Eu sou o amor"),
		t.Lyric("01:32", "And hope", "E a esperança"),
		t.br(),
		t.Lyric("01:36", "The phone rang again (hello?)", "O telefone tocou novamente (alô?)"),
		t.Lyric("01:39", "I went to answer but it wasn't my love calling", "Fui atender e não era o meu amor"),
		t.Lyric("01:44", "Is she still very mad at me?", "Será que ela ainda está muito zangada comigo?"),
		t.br(),
		t.Lyric("01:50", "What a shame", "Que pena"),
		t.Lyric("01:53", "What a shame", "Que pena"),
		t.Lyric("01:56", "What a shame", "Que pena"),
		t.Lyric("01:58", "What a shame", "Que pena"),
		t.br(),
		t.Lyric("02:01", "Because only she", "Pois só ela"),
		t.Lyric("02:03", "Understands me and helps me", "Me entende e me acode"),
		t.Lyric("02:06", "In my fall or in my rise", "Na queda ou na ascensão"),
		t.Lyric("02:07", "She's the peace to my war", "Ela é a paz da minha guerra"),
		t.Lyric("02:11", "She's my state of spirit", "Ela é meu estado de espírito"),
		t.Lyric("02:13", "She's my protection", "Ela é a minha proteção"),
		t.br(),
		t.Lyric("02:18", "What a shame", "Que pena"),
		t.Lyric("02:20", "What a shame", "Que pena"),
		t.Lyric("02:23", "What a shame", "Que pena"),
		t.Lyric("02:26", "What a shame", "Que pena"),
		t.br(),
		t.Lyric("02:30", "With her, I'm more me", "Com ela eu sou mais eu"),
		t.Lyric("02:34", "With her, I'm an angel", "Com ela eu sou um anjo"),
		t.Lyric("02:40", "With her, I'm a child", "Com ela eu sou criança"),
		t.Lyric("02:44", "I am peace", "Eu sou a paz"),
		t.Lyric("02:46", "I am love", "Eu sou o amor"),
		t.Lyric("02:47", "I am hope", "Eu sou a esperança"),
		t.Lyric("02:50", "The phone, the phone!", "O telefone, o telefone!"),
		t.br(),
		t.Lyric("02:54", "The phone rang again", "O telefone tocou novamente"),
		t.Lyric("02:58", "I went to answer but it wasn't my love calling", "Fui atender e não era o meu amor"),
		t.Lyric(
			"03:03",
			"Is she still very mad at me? (hello?)",
			"Será que ela ainda está muito zangada comigo? (alô?)"
		),
		t.br(),
		t.Lyric("03:09", "What a shame", "Que pena"),
		t.Lyric("03:12", "What a shame", "Que pena"),
		t.Lyric("03:14", "What a shame", "Que pena"),
		t.Lyric("03:17", "What a shame...", "Que pena..."),
		t.Text("(etc.)"),
	}),
	t.Song({
		title = "Mulher Brasileira",
		en_title = "Brazilian Woman",
	}, {
		t.Lyric("00:07", "Brazilian woman", "Mulher brasileira"),
		t.Lyric("00:12", "Where are you?", "Aonde é que está você?"),
		t.Lyric("00:16", "Brazilian woman", "Mulher brasileira"),
		t.Lyric("00:21", "I want you for myself", "Eu quero você pra mim"),
		t.br(),
		t.Lyric("00:26", "I want to feel your hug", "Quero sentir o seu abraço"),
		t.Lyric("00:30", "Your kiss, your affection, your love", "O seu beijo, seu carinho, o seu amor"),
		t.Lyric("00:34", "Your kindness, tenderness, and beauty", "Sua simpatia, ternura e beleza"),
		t.Lyric("00:40", "Because I need you", "Pois eu necessito de você"),
		t.br(),
		t.Lyric("00:44", "Brazilian woman", "Mulher brasileira"),
		t.Lyric("00:49", "Where are you?", "Aonde é que está você?"),
		t.Lyric("00:53", "Brazilian woman", "Mulher brasileira"),
		t.Lyric("00:58", "I want you for myself", "Eu quero você pra mim"),
		t.br(),
		t.Lyric("01:03", "Because my greatest victory would be", "Pois a minha grande vitória é conseguir"),
		t.Lyric("01:07", "To get a Brazilian woman in my life", "Botar uma mulher brasileira na minha vida"),
		t.Lyric("01:11", "Because she'll always be the first to me", "Pois para mim ela será sempre a primeira"),
		t.Lyric(
			"01:16",
			"My partner through the easy times and the hard times",
			"A companheira nas horas fáceis e difíceis"
		),
		t.br(),
		t.Lyric("01:21", "Brazilian woman", "Mulher brasileira"),
		t.Lyric("01:26", "Where are you?", "Aonde é que está você?"),
		t.Lyric("01:30", "Brazilian woman", "Mulher brasileira"),
		t.Lyric("01:35", "I want you for myself", "Eu quero você pra mim"),
		t.br(),
		t.Lyric("01:40", "Black, white, poor or rich", "Preta, branca, pobre ou rica"),
		t.Lyric("01:43", "Beautiful or ugly, you're wonderful", "Bonita ou feia você é maravilhosa"),
		t.Lyric("01:49", "I want to be the blessed fruit of you", "Eu quero ser o bendito fruto de você"),
		t.br(),
		t.Lyric("01:53", "Brazilian woman", "Mulher brasileira"),
		t.Lyric("01:58", "Where are you?", "Aonde é que está você?"),
		t.Lyric("02:02", "Brazilian woman", "Mulher brasileira"),
		t.Lyric("02:07", "I want you for myself", "Eu quero você pra mim"),
		t.Text("(instrumental)"),
		t.Lyric("02:29", "Brazilian woman", "Mulher brasileira"),
		t.Lyric("02:35", "Where are you?", "Aonde é que está você?"),
		t.Lyric("02:40", "Brazilian woman", "Mulher brasileira"),
		t.Lyric("02:44", "I want you for myself", "Eu quero você pra mim"),
		t.br(),
		t.Lyric("02:49", "(Please grow for the Brazilian woman)", "(Por favor cresçam para a mulher brasileira)"),
		t.br(),
		t.Lyric("02:54", "Brazilian woman", "Mulher brasileira"),
		t.Lyric("02:58", "Woman oh oh-oh-oh eh", "Mulher ô ô-o-o ê"),
		t.Lyric("03:02", "Brazilian woman", "Mulher brasileira"),
		t.Lyric("03:05", "Woman (hit it!)", "Mulher (senta o pau!)"),
		t.Lyric("03:08", "Brazilian woman...", "Mulher brasileira..."),
		t.Text("(etc.)"),
		t.Lyric("03:55", "Brazilian woman", "Mulher brasileira"),
		t.Lyric("04:00", "Where are you?", "Aonde é que está você?"),
		t.Lyric("04:05", "Brazilian woman", "Mulher brasileira"),
		t.Lyric("04:09", "I want you for myself", "eu quero você pra mim"),
	}),
	t.Song({
		title = "Terezinha",
		en_title = "Terezinha",
	}, {
		t.Note({
			"This song is one of the many written by Jorge Ben for his wife ",
			t.i("Domingas Terezinha Inalmo de Menezes."),
		}),
		t.Lyric("00:20", "Terezinha", "Terezinha"),
		t.Lyric("00:20", "How are you, Terê?", "Como vai você, Terê?"),
		t.Lyric("00:20", "What are you doing, Te-te?", "O que faz você, Te-te?"),
		t.Lyric("00:30", "If I were you, Terê", "Se eu fosse você Terê"),
		t.Lyric("00:35", "If I were you, Terê", "Se eu fosse você Terê"),
		t.br(),
		t.Lyric("00:39", "I would come back and ask:", "Eu voltava e dizia:"),
		t.Lyric(
			"00:41",
			"How are you, what are you doing, and where are you going?",
			"Como vai, o que faz e onde vai você?"
		),
		t.Lyric("00:46", "Because my heart beats", "Pois o meu coração bate"),
		t.Lyric("00:51", "Asking about you", "Perguntando por você"),
		t.br(),
		t.Lyric("00:56", "Terezinha", "Terezinha"),
		t.Lyric("00:59", "How are you, Terê?", "Como vai você, Terê?"),
		t.Lyric("01:03", "What are you doing?", "O que faz você?"),
		t.Lyric("01:06", "Te-te-ê!", "Te-te-ê!"),
		t.br(),
		t.Lyric("01:13", "We fail to meet so often", "Os desencontros são tantos"),
		t.Lyric("01:17", "That when you go home", "Que quando você vai pra casa"),
		t.Lyric("01:21", "I alone go to the street", "Eu sozinho vou pra rua"),
		t.Lyric("01:24", "When you look at the sun", "Quando você olhar pro Sol"),
		t.Lyric("01:29", "I alone look at the moon", "Eu sozinho, olho pra Lua"),
		t.br(),
		t.Lyric("01:32", "Te-te-terê Terezinha of my Brazil", "Te-te-terê Terezinha do meu Brasil"),
		t.Lyric("01:40", "Terê Terezinha of my Brazil", "Terê Terezinha do meu Brasil"),
		t.Lyric("02:22", "Te Terezinha of my Brazil", "Te Terezinha do meu Brasil"),
		t.Lyric("02:28", "Terê Terezinha of my Brazil", "Terê Terezinha do meu Brasil"),
		t.Lyric("02:37", "Terê Terezinha of my Brazil", "Terê Terezinha do meu Brasil"),
		t.Lyric("02:45", "Terê Terezinha of my Brazil", "Terê Terezinha do meu Brasil"),
		t.Lyric("02:53", "Terê Terezinha of my Brazil", "Terê Terezinha do meu Brasil"),
		t.Lyric("03:02", "Terê Terezinha of my Brazil", "Terê Terezinha do meu Brasil"),
	}),
	t.Song({
		title = "Força Bruta",
		en_title = "Brute Force",
	}, {
		t.Lyric("00:27", "No, no, no, no, don't say", "Não, não, não, não diga mais que"),
		t.Lyric("00:34", "That this love is like a dream", "Esse amor é como um sonho"),
		t.Lyric("00:40", "Because dreams end in the morning", "Pois se sonhos acabam de manhã"),
		t.Lyric("00:43", "And I have to wake up", "Eu tenho que acordar"),
		t.br(),
		t.Lyric("01:02", "I want to turn life into", "Quero fazer da vida"),
		t.Lyric("01:04", "A real dream", "Um sonho de verdade"),
		t.Lyric("01:06", "To live with you", "Para viver com você"),
		t.Lyric("01:07", "In the colors of love and friendship", "Nas cores do amor e da amizade"),
		t.br(),
		t.Lyric("01:10", "I want to forget the years without you", "Quero esquecer os anos sem você"),
		t.Lyric("01:12", "The memories of sadness", "A lembrança das tristezas"),
		t.Lyric("01:15", "And the grey colors of a past", "E as cores cinzas do passado"),
		t.Lyric("01:16", "Without you, my love", "Sem você, meu amor"),
		t.br(),
		t.Lyric("01:18", "Oi, no! Don't say", "Oi, não, não diga mais que"),
		t.Lyric("01:20", "That this love is like a dream, don't say", "Esse amor é como um sonho, não diga mais"),
		t.Lyric("01:26", "Because dreams end in the morning", "Pois os sonhos acabam de manhã"),
		t.Lyric("01:29", "And I have to wake up (brute force!!!)", "E eu tenho que acordar (força bruta!!!)"),
		t.br(),
		t.Lyric("01:48", "I want—to turn", "Eu quero—fazer"),
		t.Lyric("01:52", "Life—into wonder", "Da vida—uma maravilha"),
		t.Lyric("01:55", "To dream with you even knowing", "Para sonhar com você mesmo sabendo"),
		t.Lyric("01:59", "That dreams end in the morning", "Que os sonhos acabam de manhã"),
		t.Lyric("02:02", "And that I have to wake up to go to work", "E que eu tenho que acordar pra trabalhar"),
		t.Lyric("02:06", "And I won't lose you, my love, no!", "E eu não vou perder você, meu amor, não!"),
		t.br(),
		t.Lyric("02:11", "Don't say", "Não diga mais"),
		t.Lyric("02:12", "That this love is like a dream", "Que esse amor é como um sonho"),
		t.Lyric("02:16", "Don't say", "Não diga mais"),
		t.Lyric("02:18", "Because dreams end in the morning", "Pois os sonhos acabam de manhã"),
		t.Lyric(
			"02:20",
			"And I have to wake up (brute force, come on!)",
			"E eu tenho que acordar (força bruta, quero ver!)"
		),
		t.br(),
		t.Lyric("02:41", "I want to turn life into", "Quero fazer da vida"),
		t.Lyric("02:36", "A real dream", "Um sonho de verdade"),
		t.Lyric("02:41", "To live with you", "Para viver com você"),
		t.Lyric("02:43", "In the colors of love and friendship", "Nas cores do amor e da amizade"),
		t.br(),
		t.Lyric("02:48", "I want to forget the years without you", "Quero esquecer os anos sem você"),
		t.Lyric("02:51", "The memories of sadness", "A lembrança das tristezas"),
		t.Lyric("02:53", "And the ugly colors of a past", "E as cores feia do passado"),
		t.Lyric("02:55", "Without you, my love", "Sem você, meu amor"),
		t.br(),
		t.Lyric("02:56", "No, no, no, don't say (brute force!!!)", "Não, não, não diga mais que (força bruta!!!)"),
		t.Lyric("03:01", "That this love is like a dream, don't say", "Esse amor é como um sonho, não diga mais"),
		t.Lyric("03:03", "Because dreams end in the morning", "Pois os sonhos acabam de manhã"),
		t.Lyric("03:08", "And I have to wake up (brute force!!!)", "E eu tenho que acordar (força bruta!!!)"),
		t.br(),
		t.Lyric("03:27", "I want—to turn", "Eu quero—fazer"),
		t.Lyric("03:27", "Life—into wonder", "Da vida—uma maravilha"),
		t.Lyric("03:32", "To dream with you even knowing", "Para sonhar com você mesmo sabendo"),
		t.Lyric("03:40", "That dreams end in the morning", "Que os sonhos acabam de manhã"),
		t.Lyric("03:42", "And that I have to wake up to go to work", "E que eu tenho que acordar pra trabalhar"),
		t.Lyric("03:45", "And I won't lose you, my love", "E eu não vou perder você, meu amor"),
		t.br(),
		t.Lyric("03:49", "Don't say!", "Não diga mais!"),
		t.Lyric("03:50", "That this love is like a dream (hit it!)", "Que esse amor é como um sonho (senta o pau!)"),
		t.Lyric("03:56", "Because dreams end in the morning", "Pois os sonhos acabam de manhã"),
		t.Lyric("03:59", "And I have to wake up (brute force!!!)", "E eu tenho que acordar (força bruta!!!)"),
		t.br(),
		t.Lyric("04:10", "(Brute force!!!)", "(Força bruta!!!)"),
		t.Lyric("04:17", "(Down and up)", "(Desce e sobe)"),
		t.Text("(instrumental)"),
		t.Lyric("04:28", "(Brute force, brute force, brute force...)", "Força bruta, força bruta, força bruta...)"),
		t.Lyric("04:32", "Don't say", "Não diga mais"),
		t.Lyric("04:34", "That this love", "Que esse amor é como um sonho"),
		t.Lyric("04:37", "Don't say", "Não diga mais"),
		t.Lyric("04:39", "Because dreams end in the morning", "Pois os sonhos acabam de manhã"),
		t.Lyric("04:41", "And I have to wake up (the kitchen!)", "E eu tenho que acordar (a cozinha!)"),
		t.br(),
		t.Lyric("04:50", "(Don't say)", "(Não diga mais)"),
		t.Lyric("04:50", "(That this love is like a dream)", "(Que esse amor é como um sonho)"),
		t.Lyric("04:53", "(Because dreams end in the morning)", "(Pois os sonhos acabam de manhã)"),
		t.Lyric("04:57", "(And I have to wake up to go to work)", "(E eu tenho que acordar pra trabalhar)"),
	}),

	t.FootnoteSection({
		t.p({
			style = "display: inline;",
			[[
		Quote from João Parahyba: “[The nickname] Comanche was because by the end of
		the 60s I was already a flower child, hippie as hell, had huge hair, and loved
		to wear bandannas. [...] I was crazy for American indians, I knew all the tribes,
		always rooted for the indians in movies. No one talked about indians in Brazil back
		then.”
	]],
		}),
		t.a({
			href = "https://farofafa.com.br/2022/01/14/joao-parahyba-riktimista-percussionista-baterista-atabaquista-ogan/",
			style = "display: inline;",
			"(source)",
		}),
	}, {
		[[
		Charles is actually Charles Antônio Sondré, a childhood friend of Jorge who,
		according to him, was a sort of “Robin Hood of the slums.” The “Angel 45” moniker
		came from the .45 pistol he carried. The Charles from this album, Charles Jr.,
		is his son (supposedly—Jorge Ben has a Bob Dylan-like penchant for just saying
		stuff and refusing to elaborate on it...)
	]],
		t.a({
			href = "https://culturablack.com.br/quem-e-o-charles-cantado-por-jorge-ben/",
			style = "display: inline;",
			"(source)",
		}),
	}),
})
