local t = require("tmpl_lyrics")

local personnel = {
	["12-string guitar"] = "Gilberto Gil",
	["Acoustic bass"] = "Luiz Alves",
	["Acoustic guitar"] = "Gilberto Gil",
	Accordion = "Dominguinhos",
	Drums = "Roberto Silva",
	["Electric guitar"] = "Toninho Horta",
	Percussion = "Chico Batera",
}

return t.Album({
	title = "Índia",
	year = "1973",
	artist = "Gal Costa",
	genre = "MPB",

	date = {
		year = 2025,
		month = 10,
		day = 5,
	},
}, {
	t.figure.img_row({
		t.div({
			t.ZoomableImage(
				"/assets/blog/covers/1973_gal_costa_india.jpg",
				400,
				'Gal Costa album cover, depicting Gal Costa semi-nude with indigenous vests and, in all-caps blue text, the album title: "ÍNDIA"'
			),
			t.ZoomableImage(
				"/assets/blog/covers/1973_gal_costa_india_censurada.jpg",
				400,
				'Gal Costa album cover wrap, simple black text over blue blackground: "GAL COSTA ÍNDIA"'
			),
		}),
		t.figcaption.big({
			"Left: original cover, featuring Gal Costa semi-nude in indigenous vests",
			t.br(),
			"Right: bag some copies came wrapped in, after the original cover photo was censored by the military dictatorship",
		}),
		t.figcaption.small({
			"Top: original cover, featuring Gal Costa semi-nude in indigenous vests",
			t.br(),
			"Bottom: bag some copies came wrapped in, after the original cover photo was censored by the military dictatorship",
		}),
	}),
	t.Note({
		"Thank you to ",
		t.a({
			target = "_blank",
			href = "https://wandscum.com/",
			"Sylvan",
		}),
		" for the opening context and notes on the songs!",
	}),
	t.p([[
		Costa was part of the Tropicalismo movement of the late 1960s, which embraced
		an anarchic, postmodern, global art-pop—merging rock, jazz, soul, funk, psychedelic
		and avant-garde music along with a variety of Brazilian styles. This made them
		enemies among both Brazil’s ruling dictatorship, which only wanted patriotic,
		happy fun-time tunes, and the student revolutionaries, who wanted to keep Brazilian
		music pure and untainted by Western imperialism.
	]]),
	t.p([[
		Costa’s longtime friends and collaborators, Gilberto Gil and Caetano Veloso,
		spent two years in arrest and then exile. When they returned, the trio came
		together again for the 1973 Índia stage show and album. Gil served as guitarist
		and musical director, while Veloso contributed as a songwriter.
	]]),
	t.ZoomableImage("/assets/blog/gal_costa.jpg", 600, "Gal Costa sitting down, playing guitar and singing"),
	t.Subtitle('Gal Costa performing during the "Fa-Tal - Gal a Todo Vapor" show'),
	t.p([[
		In spite of the dangerous political environment, Costa continued to court
		controversy. She was photographed locking lips with Veloso’s sister, fellow
		singer Maria Bethania—and chose songs that hinted at her bisexuality. The
		regime banned one song from the radio for being too subversive, and ordered
		the scandalous semi-nude album cover be hidden under an opaque wrapper for
		distribution.
	]]),
	t.Song({
		title = "Índia",
		en_title = "Indigenous Woman",
		adapter = "José Fortuna",
		writer = { "J. A. Flores", "M. O. Guerrero" },
		arranger = "Rogério Duprat",
		conductor = "Mario Tavares",
		personnel = personnel,
	}, {
		t.Note([[
			Gal Costa never knew her father, but she had a recording of him singing this
			old sentimental song. It’s also the first of several tracks in which the bisexual
			Costa conspicuously does not change the gender of the (female) object of the
			song’s desire.
		]]),
		t.Lyric("00:23", "Índia, your hair on your low shoulders", "Índia, teus cabelos nos ombros caídos"),
		t.Lyric("00:31", "Dark as the nights without moonlight", "Negros como as noites que não tem luar"),
		t.Lyric("00:40", "Your rose lips, smiling for me", "Teus lábios de rosa, para mim, sorrindo"),
		t.Lyric("00:49", "And the sweet tenderness of your gaze", "E a doce meiguice desse teu olhar"),
		t.Lyric("00:56", "Índia with the dark skin", "Índia da pele morena"),
		t.Lyric("00:59", "I wish to kiss your tiny mouth", "Tua boca pequena eu quero beijar"),
		t.br(),
		t.Lyric("01:11", {
			"Índia of ",
			t.InlineNote("tupi", "Indigenous group of Brazil"),
			" blood, you have the scent of a flower",
		}, "Índia, sangue tupi, tens o cheiro da flor"),
		t.Lyric("01:30", "Come, I want to give you", "Vem, que eu quero te dar"),
		t.Lyric("01:41", "All of my great love", "Todo o meu grande amor"),
		t.br(),
		t.Lyric("01:56", "When I leave to far away from here", "Quando eu for embora para bem distante"),
		t.Lyric("02:04", "And the time comes to say goodbye", "E chegar a hora de dizer-te adeus"),
		t.Lyric("02:12", "Stay in my arms for a moment longer", "Fique nos meus braços só mais um instante"),
		t.Lyric("02:21", "Let my lips lock with yours", "Deixa os meus lábios se unirem aos teus"),
		t.Lyric("02:28", "Índia, I'll carry with me a longing", "Índia, levarei saudade"),
		t.Lyric("02:31", "For the happiness you gave me", "Da felicidade que você me deu"),
		t.br(),
		t.Lyric("02:43", "Índia, your image always goes with me", "Índia, tua imagem sempre comigo vai"),
		t.Lyric("03:03", "Inside my heart", "Dentro do meu coração"),
		t.Lyric("03:13", "All of my Paraguay", "Todo meu Paraguai"),
		t.Text("(repeats)"),
	}),
	t.Song({
		title = "Milho Verde (Folclore Português)",
		en_title = "Green Corn (Portuguese Folklore)",
		adapter = "Gilberto Gil",
		writer = "[Portuguese Folklore]",
		personnel = {
			["12-string guitar"] = "Gilberto Gil",
			["Acoustic bass"] = "Luiz Alves",
			["Acoustic guitar"] = "Gilberto Gil",
			Accordion = "Dominguinhos",
			Drums = "Roberto Silva",
			["Electric guitar"] = "Toninho Horta",
			Percussion = "Chacal",
		},
	}, {
		t.Note("A Portuguese folk song insinuating all manner of illicit sexuality."),
		t.Lyric("00:14", "Green corn, green corn", "Milho verde, milho verde"),
		t.Lyric("00:16", "Ah, green corn, green corn", "Ah, milho verde, milho verde"),
		t.Lyric("00:19", "Ah, green corn, corn cob", "Ah, milho verde, massaroca"),
		t.br(),
		t.Lyric("00:29", "Under the shadow of the green corn", "À sombra do milho verde"),
		t.Lyric("00:31", "Ah, under the shadow of the green corn", "Ah, à sombra do milho verde"),
		t.Lyric("00:34", "Ah, I dated a young girl", "Ah, namorei uma cachopa"),
		t.br(),
		t.Lyric("00:44", "Green corn, green corn", "Milho verde, milho verde"),
		t.Lyric("00:46", "Ah, green corn, green corn", "Ah, milho verde, milho verde"),
		t.Lyric("00:49", "Ah, tiny green corn", "Ah, milho verde miudinho"),
		t.br(),
		t.Lyric("00:57", "Under the shadow of the green corn", "À sombra do milho verde"),
		t.Lyric("01:01", "Ah, under the shadow of the green corn", "Ah, à sombra do milho verde"),
		t.Lyric("01:04", "Ah, I dated a young boy", "Ah, namorei um rapazinho"),
		t.br(),
		t.Lyric("01:13", "Green corn, green corn", "Milho verde, milho verde"),
		t.Lyric("01:16", "Ah, green corn, green corn", "Ah, milho verde, milho verde"),
		t.Lyric("01:19", "Ah, green corn, wide leaf", "Ah, milho verde, folha larga"),
		t.br(),
		t.Lyric("01:27", "Under the shadow of the green corn", "À sombra do milho verde"),
		t.Lyric("01:30", "Ah, under the shadow of the green corn", "Ah, à sombra do milho verde"),
		t.Lyric("01:34", "Ah, I dated a married woman", "Ah, namorei uma casada"),
		t.br(),
		t.Lyric("01:43", "Women that weed my corn", "Mondadeiras do meu milho"),
		t.Lyric("01:45", "Ah, women that weed my corn", "Ah, mondadeiras do meu milho"),
		t.Lyric("01:48", "Ah, weed my corn", "Ah, mondai o meu milho"),
		t.br(),
		t.Lyric("01:56", "Don't look at the path", "Não olha para o caminho"),
		t.Lyric("02:05", "Ah, don't look at the path", "Ah, não olha para o caminho"),
		t.Lyric("02:08", "Ah, for the snacks are coming soon", "Ah, que a merenda já lá vem"),
		t.br(),
		t.Lyric("02:18", "Green corn, green corn", "Milho verde, milho verde"),
		t.Lyric("02:22", "Green corn, green corn...", "Milho verde, milho verde..."),
		t.Text("(instrumental)"),
		t.Lyric("03:48", "Green corn, green corn", "Milho verde, milho verde"),
		t.Lyric("03:51", "Ah, green corn, green corn", "Ah, milho verde, milho verde"),
		t.Lyric("03:54", "Ah, tiny green corn", "Ah, milho verde miudinho"),
	}),
	t.Song({
		title = "Presente Cotidiano",
		en_title = "Everyday Life",
		writer = "Luiz Melodia",
		arranger = "Arthur Verocai",
		conductor = "Arthur Verocai",
		personnel = {
			["12-string guitar"] = "Gilberto Gil",
			["Acoustic bass"] = "Luiz Alves",
			["Acoustic guitar"] = "Gilberto Gil",
			Accordion = "Dominguinhos",
			Drums = "Roberto Silva",
			["Electric guitar"] = "Toninho Horta",
			Percussion = "Chico Batera",
			Organ = "Wagner Tiso",
		},
	}, {
		t.Note("Banned from Brazilian radio for poking fun at the dictatorship’s economic boasts."),
		t.Lyric("00:08", "Everything's loose on the air platform", "Tá tudo solto na plataforma do ar"),
		t.Lyric("00:12", "It's all there, It's all there", "Tá tudo aí, tá tudo aí"),
		t.Lyric("00:17", "Who wants to buy bananas?", "Quem vai querer comprar banana?"),
		t.Lyric("00:22", "Who wants to buy the mud?", "Quem vai querer comprar a lama?"),
		t.Lyric("00:27", "Who wants to buy the grass?", "Quem vai querer comprar a grama?"),
		t.br(),
		t.Lyric("00:32", "Everything's loose everywhere", "Tá tudo solto por aí"),
		t.Lyric("00:38", "It's all like this, It's all like this", "Tá tudo assim, tá tudo assim"),
		t.Lyric("00:43", "Those that want to die of love are mistaken", "Quem quer morrer de amor se engana"),
		t.Lyric("00:47", "Moments are moments, drama", "Momentos são momentos, drama"),
		t.Lyric("00:52", "The body is natural to the bed", "O corpo é natural da cama"),
		t.Lyric("00:57", "I'll walk a little further behind the moon", "Vou caminhar um pouco mais atrás da lua"),
		t.Lyric("01:03", "I'll walk a little further behind the street", "Vou caminhar um pouco mais atrás da rua"),
		t.br(),
		t.Lyric("01:12", "But everything flies around everywhere", "Mas tudo voa por aí"),
		t.Lyric("01:17", "On the wing of the plane", "Na asa do avião"),
		t.Lyric("01:19", "On the beak of a bird from here", "No bico de um pássaro daqui"),
		t.Lyric("01:25", "But everything spins, woe is me", "Mas tudo gira, ai de mim"),
		t.Lyric("01:29", "The ball and the spinning top", "A bola e o pião"),
		t.Lyric("01:31", "Girl in my heart", "Menina em meu coração"),
		t.br(),
		t.Lyric("01:38", "Everything's loose on the fair, a noble place", "Tá tudo solto na feira, nobre lugar"),
		t.Lyric("01:42", "It's so bad, It's so bad", "Tá tão ruim, tá tão ruim"),
		t.br(),
		t.Lyric("01:47", "Who wants to buy bananas?", "Quem vai querer comprar banana?"),
		t.Lyric("01:51", "Who wants to buy bananas?", "Quem vai querer comprar banana?"),
		t.Lyric("01:56", "Who wants to buy bananas?", "Quem vai querer comprar banana?"),
		t.Lyric("02:00", "Who wants to buy?", "Quem vai querer comprar?"),
		t.Lyric("02:05", "Who wants to?", "Quem vai querer?"),
		t.Lyric("02:07", "Who wants?", "Quem vai?"),
		t.Lyric("02:14", "Who?", "Quem?"),
		t.Lyric("02:16", "Who?", "Quem?"),
		t.Lyric("02:23", "Who?", "Quem?"),
		t.br(),
		t.Lyric("02:27", "Who wants to buy bananas?", "Quem vai querer comprar banana?"),
		t.Lyric("02:31", "Who wants to buy bananas?", "Quem vai querer comprar banana?"),
		t.Lyric("02:36", "Who wants to buy bananas?", "Quem vai querer comprar banana?"),
		t.Lyric("02:39", "Who wants to buy?", "Quem vai querer comprar?"),
		t.Lyric("02:46", "Who wants to?", "Quem vai querer?"),
		t.Lyric("02:50", "Who wants?", "Quem vai?"),
		t.Lyric("02:51", "Who?", "Quem?"),
	}),
	t.Song({
		title = "Volta",
		en_title = "Come Back",
		writer = "Lupiscinio Rodrigues",
		personnel = {
			["12-string guitar"] = "Gilberto Gil",
			["Acoustic bass"] = "Luiz Alves",
			["Acoustic guitar"] = "Gilberto Gil",
			Accordion = "Dominguinhos",
			Drums = "Roberto Silva",
			["Electric guitar"] = "Toninho Horta",
			Organ = "Tenório Jr.",
			Percussion = "Chico Batera",
		},
	}, {
		t.Lyric("00:03", "How many night I haven't slept", "Quantas noites não durmo"),
		t.Lyric("00:07", "Tossing and turning in bed", "A rolar-me na cama"),
		t.Lyric("00:11", "Feeling so many things", "A sentir tantas coisas"),
		t.Lyric("00:14", "That we can't explain when we're in love", "Que a gente não pode explicar quando ama"),
		t.br(),
		t.Lyric("00:21", "The warmth of the sheets", "O calor das cobertas"),
		t.Lyric("00:25", "Doesn't warm me right", "Não me aquece direito"),
		t.Lyric("00:30", "There's nothing in the world", "Não há nada no mundo"),
		t.Lyric("00:32", "That can remove this cold from my chest ", "Que possa afastar esse frio do meu peito"),
		t.br(),
		t.Lyric("00:41", "Come back", "Volta"),
		t.Lyric("00:44", "Come live by my side once again", "Vem viver outra vez ao meu lado"),
		t.Lyric("00:48", "I can't sleep without your arm", "Não consigo dormir sem teu braço"),
		t.Lyric("00:52", "Because my body got used to it", "Pois meu corpo está acostumado"),
		t.br(),
		t.Lyric("00:59", "Come back", "Volta"),
		t.Lyric("01:02", "Come live by my side once again", "Vem viver outra vez ao meu lado"),
		t.Lyric("01:07", "I can't sleep without your arm", "Não consigo dormir sem teu braço"),
		t.Lyric("01:11", "Because my body got used to it", "Pois meu corpo está acostumado"),
		t.br(),
		t.Lyric("01:17", "How many night I haven't slept", "Quantas noites não durmo"),
		t.Lyric("01:22", "Tossing and turning in bed", "A rolar-me na cama"),
		t.Lyric("01:27", "Feeling so many things", "A sentir tantas coisas"),
		t.Lyric("01:30", "That we can't explain when we're in love", "Que a gente não pode explicar quando ama"),
		t.br(),
		t.Lyric("01:37", "The warmth of the sheets", "O calor das cobertas"),
		t.Lyric("01:41", "Doesn't warm me right", "Não me aquece direito"),
		t.Lyric("01:46", "There's nothing in the world", "Não há nada no mundo"),
		t.Lyric("01:49", "That can remove this cold from my chest ", "Que possa afastar esse frio do meu peito"),
		t.br(),
		t.Lyric("01:57", "Come back", "Volta"),
		t.Lyric("01:59", "Come live by my side once again", "Vem viver outra vez ao meu lado"),
		t.Lyric("02:04", "I can't sleep without your arm", "Não consigo dormir sem teu braço"),
		t.Lyric("02:08", "Because my body got used to it", "Pois meu corpo está acostumado"),
		t.br(),
		t.Lyric("02:14", "Come back", "Volta"),
		t.Lyric("02:17", "Come live by my side once again", "Vem viver outra vez ao meu lado"),
		t.Lyric("02:22", "I can't sleep without your arm", "Não consigo dormir sem teu braço"),
		t.Lyric("02:26", "Because my body got used to it", "Pois meu corpo está acostumado"),
		t.br(),
		t.Lyric("02:32", "Come back", "Volta"),
		t.Lyric("02:35", "Come live by my side once again", "Vem viver outra vez ao meu lado"),
		t.Lyric("02:39", "I can't sleep without your arm", "Não consigo dormir sem teu braço"),
		t.Lyric("02:43", "Because my body got used to it", "Pois meu corpo está acostumado"),
		t.br(),
		t.Lyric("02:50", "Come back", "Volta"),
		t.Lyric("02:53", "Come live by my side once again", "Vem viver outra vez ao meu lado"),
		t.Lyric("02:57", "I can't sleep without your arm", "Não consigo dormir sem teu braço"),
		t.Lyric("03:02", "Because my body got used to it", "Pois meu corpo está acostumado"),
	}),
	t.Song({
		title = "Relance",
		en_title = "Glimpse",
		writer = { "Caetano Veloso", "Pedro Novis" },
		personnel = personnel,
	}, {
		t.Note(
			"Pay attention to the original lyrics on the right for this one, and you'll notice that there's a pattern to the way that they are constructed, in the manner of concrete poetry."
		),
		t.Lyric("00:26", "Stop, notice", "Pare, repare"),
		t.Lyric("00:35", "Cite, recite", "Cite, recite"),
		t.Lyric("00:45", "Save, fix", "Salve, ressalve"),
		t.Lyric("00:54", "Return, revolt", "Volte, revolte"),
		t.Lyric("01:03", "Treat, picture", "Trate, retrate"),
		t.Lyric("01:13", "Watch, reveal", "Vele, revele"),
		t.Lyric("01:22", "Touch, retouch", "Toque, retoque"),
		t.Lyric("01:32", "Prove, fail", "Prove, reprove"),
		t.Lyric("01:41", "Clamor, complain", "Clame, reclame"),
		t.Lyric("01:50", "Deny, reject", "Negue, renegue"),
		t.Lyric("01:59", "Jump, highlight", "Salte, ressalte"),
		t.Lyric("02:09", "Hit, hit back", "Bata, rebata"),
		t.Lyric("02:18", "Wound, refer", "Fira, refira"),
		t.Lyric("02:27", { "Break, ", t.InlineNote("break it down", "Like dancing") }, "Quebre, requebre"),
		t.Lyric("02:37", { "Move, ", t.InlineNote("move it", "Like dancing (again)") }, "Mexa, remexa"),
		t.Lyric("02:46", "Draft, twerk", "Bole, rebole"),
		t.Lyric("02:56", "Return, revolve", "Volva, revolva"),
		t.Lyric("03:05", "Run, resort", "Corra, recorra"),
		t.Lyric("03:14", "Kill, finish", "Mate, remate"),
		t.br(),
		t.Lyric("03:24", "Die, be reborn!", "Morra, renasça!"),
		t.Lyric("03:31", "Die, be reborn!", "Morra, renasça!"),
		t.Lyric("03:38", "Die, be reborn!", "Morra, renasça!"),
		t.Lyric("03:45", "Die, be reborn!", "Morra, renasça!"),
		t.Lyric("03:52", "Die, be reborn!", "Morra, renasça!"),
		t.Lyric("03:59", "Die, be reborn!", "Morra, renasça!"),
		t.Lyric("04:06", "Die, be reborn!", "Morra, renasça!"),
		t.Lyric("04:13", "Die, be reborn!", "Morra, renasça!"),
		t.Lyric("04:20", "Die, be reborn!", "Morra, renasça!"),
		t.Lyric("04:27", "Die, be reborn!", "Morra, renasça!"),
		t.Lyric("04:34", "Die, be reborn!", "Morra, renasça!"),
		t.Lyric("04:40", "Die, be reborn!", "Morra, renasça!"),
		t.Lyric("04:48", "Die, be reborn!", "Morra, renasça!"),
		t.Lyric("04:55", "Die, be reborn!", "Morra, renasça!"),
	}),
	t.Song({
		title = "Da Maior Importância",
		en_title = "Of the Greatest Importance",
		writer = "Caetano Veloso",
		personnel = personnel,
	}, {
		t.Lyric("00:19", "It was a small moment, a quirk of yours", "Foi um pequeno momento, um jeito"),
		t.Lyric("00:24", "Something like that", "Uma coisa assim"),
		t.Lyric("00:28", "A movement and then you couldn't anymore", "Era um movimento que aí você não pode mais"),
		t.Lyric("00:35", "Couldn't like me right", "Gostar de mim direito"),
		t.br(),
		t.Lyric("00:42", "It would have been on the beach, fear", "Teria sido na praia, medo"),
		t.Lyric("00:47", "It will be a mistake", "Vai ser um erro"),
		t.Lyric("00:49", "A word, the wrong word", "Uma palavra, a palavra errada"),
		t.br(),
		t.Lyric("00:56", "Nothing, nothing", "Nada, nada"),
		t.Lyric("01:01", "Practically nothing, nothing", "Basta nada, nada"),
		t.Lyric(
			"01:05",
			"And I almost don't like it, I don't even like it now",
			"E eu quase não gosto, já nem gosto"
		),
		t.Lyric(
			"01:10",
			{ "The way ", t.InlineNote("you", 'The "you" is a woman'), " were suddenly looked at by us" },
			"Do jeito que de repente você foi olhada por nós"
		),
		t.br(),
		t.Lyric("01:23", {
			t.InlineNote("Because I'm shy and there was a thing", "This line makes it clear that it's a man speaking"),
		}, "Porque eu sou tímido e teve um negócio"),
		t.Lyric("01:28", "Where you asked my sign", "De você perguntar o meu signo"),
		t.Lyric("01:31", "When there wasn't any sign at all", "Quando não havia, signo nenhum"),
		t.Lyric("01:40", "Scorpio, Sagittarius, or whatever", "Escorpião, sagitário, não sei que lá"),
		t.br(),
		t.Lyric(
			"01:51",
			"We just started talking about stupid things, idle chit-chat",
			"Ficou um papo de otário, um papo"
		),
		t.Lyric("01:56", "It was going well", "Ia sendo bom"),
		t.Lyric(
			"02:00",
			"It's so hard, so simple, hard, so easy",
			"É tão difícil, tão simples, difícil, tão fácil"
		),
		t.Lyric("02:05", "All of a sudden being such a huge thing", "De repente ser uma coisa tão grande"),
		t.br(),
		t.Lyric("02:13", "Of the greatest importance", "Da maior importância"),
		t.Lyric(
			"02:18",
			"There must be some kind of thing for you and me",
			"Deve haver uma transa qualquer pra você e pra mim"
		),
		t.Lyric("02:26", "Between us", "Entre nós"),
		t.Lyric(
			"02:32",
			"And you throwing it away and now go away, go",
			"E você jogando fora e agora vá embora, vá"
		),
		t.br(),
		t.Lyric("02:41", "There must be some kind of way, some time", "Deve haver um jeito qualquer, uma hora"),
		t.Lyric("02:49", {
			t.InlineNote(
				"There's always a man for a woman",
				'Verse from the song "O Grande Amor," by Antônio Carlos Jobim & Vinicius de Moraes'
			),
		}, "Há sempre um homem, para uma mulher"),
		t.Lyric("02:59", {
			t.InlineNote(
				"There are ten women for each man",
				'Verse from the song "Ninguém Tasca (O Gavião)" by Pedrinho Rodrigues'
			),
		}, "Há dez mulheres para cada um"),
		t.Lyric("03:03", {
			t.InlineNote(
				"A woman is always a woman",
				'Verse from the song "Mulher, Sempre Mulher" by Vinicius de Moraes'
			),
			", etc., so on, so forth",
		}, "Uma mulher é sempre uma mulher, etc. e tal"),
		t.br(),
		t.Lyric(
			"03:12",
			"Just like how there exist flying saucers and the darkness of the future",
			"Assim como existe disco voador e o escuro do futuro"
		),
		t.Lyric("03:19", "May exist in what depends", "Pode haver no que está dependendo"),
		t.Lyric("03:25", "On a pure little moment of love", "De um pequeno momento puro de amor"),
		t.br(),
		t.Lyric(
			"03:34",
			"But you weren't up for it, and now it's not me that's going to",
			"Mas você não teve pique, e agora não sou eu quem vai"
		),
		t.Lyric("03:43", "Tell you to stay, you weren't up for it", "Lhe dizer que fique, você não teve pique"),
		t.Lyric(
			"03:48",
			"And now it's not me that's going to tell you to stay",
			"E agora não sou eu quem vai lhe dizer que fique"
		),
		t.Lyric(
			"03:56",
			"But you weren't up for it, and now it's not me that's going to",
			"Mas você não teve pique e agora não sou eu quem vai"
		),
		t.Lyric("04:09", "Tell you to stay, it's not me that's going to", "Lhe dizer que fique, não sou eu quem vai"),
		t.Lyric("04:18", "You weren't up for it", "Você não teve pique"),
		t.Lyric("04:22", "It's not me that's going to", "Não sou eu quem vai"),
		t.Lyric("04:26", "Tell you to stay", "Lhe dizer que fique"),
		t.Lyric("04:31", "It's not me that's going to", "Não sou eu quem vai"),
		t.Lyric(
			"04:35",
			"It's not me that's going to tell you that you weren't up for it",
			"Não sou eu quem vai lhe dizer que você não teve pique"
		),
		t.Lyric("04:42", "It's not me", "Não sou eu"),
		t.br(),
		t.Lyric("04:55", "To stay", "Que fique"),
		t.Lyric("04:57", "It's not me that's going to", "Não sou eu quem vai"),
		t.Lyric("05:01", "But you weren't up for it", "Mas você não teve pique"),
		t.Lyric("05:05", "It's not me that's going to", "Não sou eu quem vai"),
	}),
	t.Song({
		title = "Passarinho",
		en_title = "Little Bird",
		writer = "Tuzé de Abreu",
		personnel = personnel,
	}, {
		t.Lyric("00:40", "Sing like a bird", "Cantar como um passarinho"),
		t.Lyric("00:46", "In the early morning", "De manhã cedinho"),
		t.Lyric("00:52", "On a branch in the grove", "Lá na galha do arvoredo"),
		t.Lyric("00:58", "By the river shore", "Na beira do rio"),
		t.br(),
		t.Lyric("01:56", "Flap your wings, little bird", "Bate as asas, passarinho"),
		t.Lyric("02:00", "Because I want to fly", "Que eu quero voar"),
		t.Lyric("02:06", "Flap your wings, little bird", "Bate as asas, passarinho"),
		t.Lyric("02:12", "Because I want to fly", "Que eu quero voar"),
		t.br(),
		t.Lyric("02:19", "Take me to the girl's window", "Me leva na janela da menina"),
		t.Lyric("02:25", "Because I want to fly", "Que eu quero amar"),
		t.Lyric("02:31", "Take me to her window", "Me leva na janela dela"),
		t.Lyric("02:37", "Because I want to peek", "Que eu quero espiar"),
		t.Lyric("02:43", "Take me to the girl's window", "Me leva na janela da menina"),
		t.Lyric("02:49", "Because I want to sing", "Que eu quero cantar"),
		t.br(),
		t.Lyric("02:55", "Sing like a bird", "Cantar como um passarinho"),
		t.Lyric("03:01", "In the early morning", "De manhã cedinho"),
		t.Lyric("03:07", "On a branch in the grove", "Lá na galha do arvoredo"),
		t.Lyric("03:13", "By the river shore", "Na beira do rio"),
		t.br(),
		t.Lyric("03:53", "Sing like a bird", "Cantar como um passarinho"),
		t.Lyric("03:59", "In the early morning", "De manhã cedinho"),
		t.Lyric("04:05", "On a branch in the grove", "Lá na galha do arvoredo"),
		t.Lyric("04:10", "By the river shore", "Na beira do rio"),
		t.br(),
		t.Lyric("04:17", "Sing like a bird", "Cantar como um passarinho"),
		t.Lyric("04:23", "Like a bird", "Como um passarinho"),
		t.Lyric("04:37", "Sing like a bird", "Cantar como um passarinho"),
		t.Lyric("04:42", "Like a bird", "Como um passarinho"),
		t.Lyric("04:48", "Like a bird", "Como um passarinho"),
	}),
	t.Song({
		title = "Pontos de Luz",
		en_title = "Motes of Light",
		writer = { "Jards Macalé", "Waly Sailormoon" },
		arranger = "Arthur Verocai",
		conductor = "Arthur Verocai",
		personnel = {
			["12-string guitar"] = "Gilberto Gil",
			["Acoustic bass"] = "Luiz Alves",
			["Acoustic guitar"] = "Gilberto Gil",
			Accordion = "Dominguinhos",
			Drums = "Roberto Silva",
			["Electric guitar"] = "Toninho Horta",
			Organ = "Tenório Jr.",
			Percussion = "Chico Batera",
		},
	}, {
		t.Lyric("00:14", "I feel content", "Me sinto contente"),
		t.Lyric("00:17", "I feel very content", "Me sinto muito contente"),
		t.Lyric("00:22", "I feel completely content", "Me sinto completamente contente"),
		t.Lyric("00:24", "I dare say: completely content", "Ouso dizer: completamente contente"),
		t.br(),
		t.Lyric("00:27", "I'd even say", "Me arrisco a falar"),
		t.Lyric("00:31", "I feel happy", "Me sinto feliz"),
		t.Lyric("00:35", "I feel very happy", "Me sinto muito feliz"),
		t.Lyric("00:40", "I feel completely happy", "Me sinto completamente feliz"),
		t.Lyric("00:42", "I dare say: completely happy", "Ouso dizer: completamente feliz"),
		t.br(),
		t.Lyric("00:58", "I feel content", "Me sinto contente"),
		t.Lyric("01:02", "I feel very content", "Me sinto muito contente"),
		t.Lyric("01:06", "I feel completely content", "Me sinto completamente contente"),
		t.Lyric("01:08", "I dare say: completely content", "Ouso dizer: completamente contente"),
		t.br(),
		t.Lyric("01:12", "I'd even say", "Me arrisco a falar"),
		t.Lyric("01:16", "I feel happy", "Me sinto feliz"),
		t.Lyric("01:19", "I feel very happy", "Me sinto muito feliz"),
		t.Lyric("01:24", "I feel completely happy", "Me sinto completamente feliz"),
		t.Lyric("01:26", "I dare say: completely happy", "Ouso dizer: completamente feliz"),
		t.br(),
		t.Lyric("01:37", "I feel happy", "Me sinto feliz"),
		t.Lyric("01:46", "I feel content", "Me sinto contente"),
		t.Lyric("01:55", "I feel happy", "Me sinto feliz"),
		t.Lyric("02:05", "I feel completely", "Me sinto completamente"),
	}),
	t.Song({
		title = "Desafinado",
		en_title = "Out of Tune",
		writer = { "Antonio Carlos Jobim", "Newton Mendonça" },
		personnel = {
			["Acoustic bass"] = "Luiz Alves",
			["Acoustic guitar"] = "Roberto Menescal",
			Accordion = "Dominguinhos",
			Drums = "Roberto Silva",
			["Electric guitar"] = "Toninho Horta",
			Percussion = "Chico Batera",
		},
	}, {
		t.Note(
			"A Bossa Nova standard, kind of the theme song for the whole genre. But in this context, given Costa’s position as a musical, political, and sexual dissident, ending with this defiant declaration to be one of the “out of tune ones” takes on some added dimensions."
		),
		t.Lyric("00:13", "When you say that I go out of tune, love", "Se você disser que eu desafino, amor"),
		t.Lyric("00:20", "Know that this causes me immense pain", "Saiba que isso em mim provoca imensa dor"),
		t.Lyric("00:28", "Only the privileged have ears like yours", "Só privilegiados tem ouvido igual ao seu"),
		t.Lyric("00:35", "I have only what God gave to me", "Eu possuo apenas o que Deus me deu"),
		t.br(),
		t.Lyric("00:43", "If you insist in categorizing", "Se você insiste em classificar"),
		t.Lyric("00:51", "My behaviour as anti-musical", "Meu comportamento de anti-musical"),
		t.Lyric("00:58", "Even if lying, I must argue", "Eu, mesmo mentindo, devo argumentar"),
		t.Lyric(
			"01:06",
			"That this is Bossa Nova, this is very natural",
			"Que isso é bossa nova, isso é muito natural"
		),
		t.br(),
		t.Lyric("01:13", "What you don't know, and never suspected", "O que você não sabe, nem sequer pressente"),
		t.Lyric(
			"01:21",
			"Is that the out of tune ones also have a heart",
			"É que os desafinados também tem um coração"
		),
		t.Lyric(
			"01:28",
			{ "I photographed you with my ", t.InlineNote("Rolleiflex", "Old line of analog cameras") },
			"Fotografei você na minha Rolleiflex"
		),
		t.Lyric("01:35", {
			"And your great ingratitude was ",
			t.InlineNote("revealed", "To “develop” a photo in Portuguese is to “reveal” it. It's a pun."),
		}, "Revelou-se a sua enorme ingratidão"),
		t.br(),
		t.Lyric(
			"01:43",
			"The only person you can't talk like this about is my love",
			"Só não poderá falar assim do meu amor"
		),
		t.Lyric("01:51", "He's the greatest you can find, alright?", "Ele é o maior que você pode encontrar, viu?"),
		t.Lyric(
			"01:58",
			"You, with your music, forgot the main thing",
			"Você, com a sua música, esqueceu do principal"
		),
		t.Lyric(
			"02:05",
			"That in the chest of the out of tune ones, the bottom of the chest, it beats silently",
			"Que no peito dos desafinados, no fundo do peito, bate calado"
		),
		t.Lyric(
			"02:13",
			"That in the chest of the out of tune ones, a heart also beats",
			"Que no peito dos desafinados também bate um coração"
		),
	}),
})
