local t = require("tmpl_lyrics")

return t.Album({
	title = "PEDAGIOS Y CARONAS",
	artist = "Tangolo Mangos",
	year = 2026,
	genre = { "Indie Rock", "Neo-Psychedelia", "Psychedelic Rock" },

	date = {
		year = 2026,
		month = 5,
		day = 24,
	},
}, {
	t.figure({
		t.img({
			src = "/assets/blog/covers/2026_tangolo_mangos_pedagios_y_caronas.jpg",
			width = 400,
			alt = "Cover for PEDAGIOS Y CARONAS, depicting a monochrome image of a man running after a street dog",
		}),
		t.figcaption({
			"The ",
			t.i("carrocinhas"),
			" were a cruel fixture of 20th century Brazil",
		}),
	}),
	t.Song({
		title = "Armadura Armadilha",
		en_title = "Trap Armor",
		artist = "Tangolo Mangos",
		writer = "Felipe Vaqueiro",
	}, {
		t.Lyric("00:24", "The weight of this armor pulls me back", "O peso dessa armadura me puxa pra trás"),
		t.Lyric(
			"00:26",
			"I no longer want to prune myself, shield myself, arm myself",
			"Não quero mais me podar, me blindar, me armar"
		),
		t.Lyric(
			"00:29",
			"Should arrows follow me, they'll pass right through",
			"Mesmo que a flecha me siga, vai atravessar"
		),
		t.Lyric("00:31", "Ricochet in the air", "Ricocheteia no ar"),
		t.br(),
		t.Lyric("00:34", "No helmet, vest, undressed of chaos", "Sem capacete, colete, despido de caos"),
		t.Lyric(
			"00:37",
			"I no longer want to throw myself into this gas cloud",
			"Não quero mais me jogar nessa nuvem de gás"
		),
		t.Lyric("00:39", "The freedom that shall echo in the heavens", "A liberdade que há de ecoar pelos céus"),
		t.Lyric("00:42", "Free of the weight of metals", "Sem o peso dos metais"),
		t.Lyric("00:45", "They pull you back", "Eles te puxam pra trás"),
		t.Lyric("00:49", "Back!", "Pra trás!"),
		t.Text("(instrumental)"),
		t.Lyric("01:31", "The weight of this armor pulls me back", "O peso dessa armadura me puxa pra trás"),
		t.Lyric(
			"01:34",
			"I no longer want to prune myself, shield myself, arm myself",
			"Não quero mais me blindar, me podar, me armar"
		),
		t.Lyric(
			"01:36",
			"Should arrows follow me, they'll pass right through",
			"Mesmo que a flecha me siga, vai atravessar"
		),
		t.Lyric("01:39", "Ricochet in the air", "Ricocheteia no ar"),
		t.br(),
		t.Lyric("01:41", "No helmet, vest, undressed of chaos", "Sem capacete, colete, despido de caos"),
		t.Lyric(
			"01:44",
			"I no longer want to throw myself into this gas cloud",
			"Não quero mais me jogar nessa nuvem de gás"
		),
		t.Lyric("01:47", "The freedom that shall echo in the heavens", "A liberdade que há de ecoar pelo céu"),
		t.Lyric("01:50", "Free of the weight of metals", "Sem o peso dos metais"),
		t.Lyric("01:52", "They pull you back", "Eles te puxam pra trás"),
		t.Lyric("01:56", "Back!", "De trás!"),
	}),
	t.Song({
		title = "Eu e Você (Skarência)",
		en_title = "Me and You (Skaring)",
		artist = "Tangolo Mangos",
		writer = "Felipe Vaqueiro",
	}, {
		t.Note([[
			The title is a pun with the word “ska” (the genre) and “carência” (literally
			“a lack of something,” but frequently used to refer to an emotional neediness—the
			state of missing one's lover.)
		]]),
		t.Lyric("00:00", "I want to fill you with affection", "Eu quero te encher de dengo"),
		t.Lyric("00:00", "I want to get all lovey-dovey", "Quero ficar molengo no seu dengo"),
		t.Lyric("00:00", "And I know you know that", "E eu sei que você sabe disso"),
		t.br(),
		t.Lyric("00:00", "I fell under your spell", "Eu caí no seu feitiço"),
		t.Lyric("00:00", "Trip and think on this", "Castele e pense nisso"),
		t.Lyric(
			"00:00",
			"What's the substance that causes this vice?",
			"Qual será a substância que te causa o vício?"
		),
		t.br(),
		t.Lyric("00:00", "Is it serotonin?", "Será serotonina?"),
		t.Lyric("00:00", "Is it oxytocin?", "Seria ocitocina?"),
		t.Lyric("00:00", "Is it dopamine?", "Seria dopamina?"),
		t.Lyric("00:00", "Strychnine, caffeine, psilocybin?", "Estricnina, cafeína, psilocibina?"),
		t.br(),
		t.Lyric("00:00", "There's no vaccine", "Não existe vacina"),
		t.Lyric("00:00", "At least not yet", "Ao menos não ainda"),
		t.Lyric("00:00", "That can stop my body", "Que evite o meu corpo"),
		t.Lyric("00:00", "From struggling not to", "De passar pelo sufoco"),
		t.Lyric("00:00", "Want to have your body", "De querer todo seu corpo"),
		t.Lyric("00:00", "Rolling in my tongue", "Passeando pela minha língua"),
		t.br(),
		t.Lyric("00:00", "I want to be inside of there", "Eu queria estar lá dentro"),
		t.Lyric("00:00", "Being your sustenance", "Sendo seu alimento"),
		t.Lyric("00:00", "One of these days", "Qualquer dia desses"),
		t.Lyric("00:00", "With disposition and time, I will", "Com disposição e tempo, eu vou ser"),
		t.Lyric("00:00", "Me and you", "Eu e você"),
		t.br(),
		t.Lyric("00:00", "Is it serotonin?", "Será serotonina?"),
		t.Lyric("00:00", "Is it oxytocin?", "Seria ocitocina?"),
		t.Lyric("00:00", "Is it dopamine?", "Seria dopamina?"),
		t.Lyric("00:00", "Strychnine, caffeine, psilocybin?", "Estricnina, cafeína, psilocibina?"),
		t.br(),
		t.Lyric("00:00", "There's no vaccine", "Não existe vacina"),
		t.Lyric("00:00", "At least not yet", "Ao menos não ainda, não"),
		t.Lyric("00:00", "That can stop my body", "Que evite o meu corpo"),
		t.Lyric("00:00", "From struggling not to", "De passar pelo sufoco"),
		t.Lyric("00:00", "Want to have your body", "De querer todo seu corpo"),
		t.Lyric("00:00", "Rolling in my tongue", "Passeando pela minha língua"),
		t.br(),
		t.Lyric("00:00", "I want to be inside of there", "Eu queria estar lá dentro"),
		t.Lyric("00:00", "Being your sustenance", "Sendo seu alimento"),
		t.Lyric("00:00", "One of these days", "Qualquer dia desses"),
		t.Lyric("00:00", "With disposition and time, I will", "Com disposição e tempo, eu vou ser"),
		t.Lyric("00:00", "Me and you", "Eu e você"),
	}),
	t.Song({
		title = "Armadura Armadilha",
		en_title = "Trap Armor",
		artist = "Tangolo Mangos",
		writer = "Felipe Vaqueiro",
	}, {
		t.Lyric("00:00", "Sometimes the Sun likes to come out to play"),
		t.Lyric("00:00", "Greet him with ohayo saravá"),
		t.Lyric("00:00", "Sometimes it hides itself in cloudy days"),
		t.Lyric("00:00", "Sometimes it makes me feel like a star"),
		t.br(),
		t.Lyric("00:00", "Red dwarf", "Anã vermelha"),
		t.Lyric("00:00", "My star", "A minha estrela"),
		t.Lyric("00:00", "No longer shines", "Já não brilha"),
		t.Lyric("00:00", "It'll go out", "Vai se apagar"),
		t.Lyric("00:00", "Throughout the vacuum", "Pelo vácuo"),
		t.Lyric("00:00", "In a desert of star sand", "Num deserto de areia estelar"),
		t.br(),
		t.Lyric("00:00", "Sometimes it feels like dying"),
		t.Lyric("00:00", "But then the Sun shine on"),
		t.Lyric("00:00", "Some nights it feels like falling"),
		t.Lyric("00:00", "Until you see the Sun"),
		t.br(),
		t.Lyric("00:00", "Sometimes it feels like dying"),
		t.Lyric("00:00", "But then the Sun shine on"),
		t.Lyric("00:00", "Some nights it feels like falling"),
		t.Lyric("00:00", "Until you see the Sun"),
		t.br(),
		t.Lyric("00:00", "Tomorrow", "Amanhã"),
		t.Lyric("00:00", "You will", "Você vai"),
		t.Lyric("00:00", "Wake up", "Acordar"),
		t.Lyric("00:00", "Get tired", "Se cansar"),
		t.Lyric("00:00", "Work", "Trabalhar"),
		t.Lyric("00:00", "Return", "Retornar"),
		t.Lyric("00:00", "Rest", "Dеscansar"),
		t.Lyric("00:00", "Lie down", "Se deitar"),
		t.Lyric("00:00", "In the morning", "De manhã"),
		t.Lyric("00:00", "Not knowing", "Sem saber"),
		t.Lyric("00:00", "The reason", "O porquê"),
		t.Lyric("00:00", "Why you're so tired", "De estar tão cansado"),
		t.Lyric("00:00", "I slept but my battery is worn out", "Eu dormi mas minha bateria viciou"),
		t.Lyric("00:00", "Broke my charger", "Quebrou o meu carregador"),
		t.br(),
		t.Lyric("00:00", "Sometimes the Sun likes to invite the rain"),
		t.Lyric("00:00", "Greet them with ohayo saravá"),
		t.Lyric("00:00", "If they don't know how to translate you say"),
		t.Lyric("00:00", "Salam alaykum, shalom, olá"),
		t.br(),
		t.Lyric("00:00", "Our star", "A nossa estrela"),
		t.Lyric("00:00", "Will be older", "Será mais velha"),
		t.Lyric("00:00", "And one day its heat will dissipate", "E um dia o seu calor dissipará"),
		t.Lyric("00:00", "Throughout the vacuum", "Pelo vácuo"),
		t.Lyric("00:00", "Each day closer", "Cada vez mais perto"),
		t.Lyric("00:00", "And I know it'll take a while", "E eu sei que ainda demora"),
		t.Lyric(
			"00:00",
			"We have well over a thousand hours to get it right this time!",
			"Temos bem mais de mil horas pra tentar acertar dessa vez!"
		),
		t.br(),
		t.Lyric("00:00", "Sometimes it feels like dying"),
		t.Lyric("00:00", "But then the Sun shine on"),
		t.Lyric("00:00", "Some nights it feels like falling"),
		t.Lyric("00:00", "Until you see the Sun"),
		t.br(),
		t.Lyric("00:00", "Sometimes it feels like dying"),
		t.Lyric("00:00", "But then the Sun shine on"),
		t.Lyric("00:00", "Some nights it feels like falling"),
		t.Lyric("00:00", "Until you see the Sun"),
		t.br(),
		t.Lyric("00:00", "Tomorrow", "Amanhã"),
		t.Lyric("00:00", "You will", "Você vai"),
		t.Lyric("00:00", "Wake up", "Acordar"),
		t.Lyric("00:00", "Get tired", "Se cansar"),
		t.Lyric("00:00", "Work", "Trabalhar"),
		t.Lyric("00:00", "Return", "Retornar"),
		t.Lyric("00:00", "Rest", "Dеscansar"),
		t.Lyric("00:00", "Lie down", "Se deitar"),
		t.Lyric("00:00", "In the morning", "De manhã"),
		t.Lyric("00:00", "Not knowing", "Sem saber"),
		t.Lyric("00:00", "The reason", "O porquê"),
		t.Lyric("00:00", "Why you're so tired", "De estar tão cansado"),
		t.Lyric("00:00", "I slept but my battery is worn out", "Eu dormi mas minha bateria viciou"),
		t.Lyric("00:00", "Broke my charger", "Quebrou o meu carregador"),
		t.Lyric("00:00", "(Broke my charger)", "(Quebrou o meu carregador)"),
		t.br(),
		t.Lyric("00:00", "Sometimes it feels like dying"),
		t.Lyric("00:00", "But then the Sun shine on"),
		t.Lyric("00:00", "Some nights it feels like falling"),
		t.Lyric("00:00", "Until you see the Sun"),
		t.br(),
		t.Lyric("00:00", "Sometimes it feels like dying"),
		t.Lyric("00:00", "But then the Sun shine"),
	}),
	t.Song({
		title = "Dominó (Citação: “Falando Nisso”)",
		en_title = "",
		artist = "Tangolo Mangos",
		writer = { "Bruno Fechine", "Valentim Frateschi" },
	}, {
		t.Lyric("00:00", "", "Você leu minha pedra e então jogou"),
		t.Lyric("00:00", "", "Forçando ela na mesa"),
		t.Lyric("00:00", "", "Vem cá, vem me abraçar"),
		t.Lyric("00:00", "", "Pode encher o copo e continuar aí"),
		t.Lyric("00:00", "", "De dupla a gente fica"),
		t.Lyric("00:00", "", "Até alguém tirar"),
		t.br(),
		t.Lyric("00:00", "", "Não se anima não"),
		t.Lyric("00:00", "", "Tu não ganha não"),
		t.Lyric("00:00", "", "Pra tirar nós dois"),
		t.Lyric("00:00", "", "Só se passar com pedra na mão"),
		t.br(),
		t.Lyric("00:00", "", "Se trouxer teu gato só"),
		t.Lyric("00:00", "", "Cuida do cucão bravo e"),
		t.Lyric("00:00", "", "Pode levantar que a ponta é nossa"),
		t.Lyric("00:00", "", "Bati sua bucha, colega!"),
		t.br(),
		t.Lyric("00:00", "", "Você veio cheio de moral pra mim"),
		t.Lyric("00:00", "", "Botou sua bucha em cima"),
		t.Lyric("00:00", "", "E fez eu me irritar"),
		t.Lyric("00:00", "", "Eu tomei um gole e me precipitei"),
		t.Lyric("00:00", "", "Matei os reis da mesa"),
		t.Lyric("00:00", "", "Pode chorar, comemorar!"),
		t.Lyric("00:00", "", "Bota o dedo na minha cara, mas"),
		t.br(),
		t.Lyric("00:00", "", "Não se anima não"),
		t.Lyric("00:00", "", "Tu não ganha não"),
		t.Lyric("00:00", "", "Pra tirar nós dois"),
		t.Lyric("00:00", "", "Só se passar com pedra na mão"),
		t.br(),
		t.Lyric("00:00", "", "Se trouxer teu gato só"),
		t.Lyric("00:00", "", "Cuida do cucão bravo e"),
		t.Lyric("00:00", "", "Pode levantar que a ponta é nossa"),
		t.Lyric("00:00", "", "Bati sua bucha, colega!"),
		t.br(),
		t.Lyric("00:00", "", "Me desculpe se por vez ou outra eu não entender"),
		t.Lyric("00:00", "", "Que o jogo não é meu só por ganância"),
		t.Lyric("00:00", "", "Ou se de repente eu não entender"),
		t.Lyric("00:00", "", "Que minha ponta tá atrapalhando a sua jogada"),
		t.Lyric("00:00", "", "Mas eu juro que a de fora é nossa"),
		t.Lyric("00:00", "", "E dessa vez eu juro, eu vou prestar mais atenção"),
		t.br(),
		t.Lyric("00:00", "", "E te entregar de lasquinê"),
		t.Lyric("00:00", "", "De mão beijada pra você"),
		t.Lyric("00:00", "", "Essa rodada"),
		t.Lyric("00:00", "", "Vamo mais um?"),
	}),
})
